/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) casadi_kf_baseline4_meas_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s2[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[24] = {0, 8, 17, 26, 30, 34, 38, 46, 55, 64, 68, 72, 76, 84, 93, 102, 106, 110, 114, 122, 131, 140, 144, 148};
static const casadi_int casadi_s4[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s5[12] = {1, 9, 18, 39, 47, 56, 77, 85, 94, 115, 123, 132};
static const casadi_int casadi_s6[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s7[12] = {2, 10, 19, 40, 48, 57, 78, 86, 95, 116, 124, 133};
static const casadi_int casadi_s8[10] = {3, 3, 0, 0, 2, 4, 1, 2, 1, 2};
static const casadi_int casadi_s9[20] = {11, 20, 27, 31, 35, 49, 58, 65, 69, 73, 87, 96, 103, 107, 111, 125, 134, 141, 145, 149};
static const casadi_int casadi_s10[10] = {3, 3, 0, 2, 2, 4, 0, 2, 0, 2};
static const casadi_int casadi_s11[24] = {3, 12, 21, 28, 32, 36, 41, 50, 59, 66, 70, 74, 79, 88, 97, 104, 108, 112, 117, 126, 135, 142, 146, 150};
static const casadi_int casadi_s12[10] = {3, 3, 0, 2, 4, 4, 0, 1, 0, 1};
static const casadi_int casadi_s13[20] = {4, 13, 22, 29, 33, 42, 51, 60, 67, 71, 80, 89, 98, 105, 109, 118, 127, 136, 143, 147};
static const casadi_int casadi_s14[16] = {0, 1, 2, 6, 7, 8, 9, 13, 14, 15, 16, 20, 21, 22, 23, 27};
static const casadi_int casadi_s15[16] = {7, 16, 25, 37, 45, 54, 63, 75, 83, 92, 101, 113, 121, 130, 139, 151};
static const casadi_int casadi_s16[177] = {28, 22, 0, 12, 24, 36, 40, 44, 48, 68, 92, 112, 115, 118, 122, 125, 128, 132, 135, 138, 142, 145, 148, 152, 152, 0, 1, 2, 7, 8, 9, 14, 15, 16, 21, 22, 23, 0, 1, 2, 7, 8, 9, 14, 15, 16, 21, 22, 23, 0, 1, 2, 7, 8, 9, 14, 15, 16, 21, 22, 23, 3, 10, 17, 24, 4, 11, 18, 25, 5, 12, 19, 26, 1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 22, 23, 24, 25, 26, 0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 0, 1, 2, 3, 4, 7, 8, 9, 10, 11, 14, 15, 16, 17, 18, 21, 22, 23, 24, 25, 0, 1, 2, 0, 1, 2, 0, 1, 2, 6, 7, 8, 9, 7, 8, 9, 7, 8, 9, 13, 14, 15, 16, 14, 15, 16, 14, 15, 16, 20, 21, 22, 23, 21, 22, 23, 21, 22, 23, 27};
static const casadi_int casadi_s17[183] = {22, 28, 0, 8, 17, 26, 30, 34, 37, 38, 46, 55, 64, 68, 72, 75, 76, 84, 93, 102, 106, 110, 113, 114, 122, 131, 140, 144, 148, 151, 152, 0, 1, 2, 7, 8, 9, 10, 11, 0, 1, 2, 6, 7, 8, 9, 10, 11, 0, 1, 2, 6, 7, 8, 9, 10, 11, 3, 6, 7, 8, 4, 6, 7, 8, 5, 6, 7, 11, 0, 1, 2, 7, 8, 12, 13, 14, 0, 1, 2, 6, 7, 8, 12, 13, 14, 0, 1, 2, 6, 7, 8, 12, 13, 14, 3, 6, 7, 8, 4, 6, 7, 8, 5, 6, 7, 14, 0, 1, 2, 7, 8, 15, 16, 17, 0, 1, 2, 6, 7, 8, 15, 16, 17, 0, 1, 2, 6, 7, 8, 15, 16, 17, 3, 6, 7, 8, 4, 6, 7, 8, 5, 6, 7, 17, 0, 1, 2, 7, 8, 18, 19, 20, 0, 1, 2, 6, 7, 8, 18, 19, 20, 0, 1, 2, 6, 7, 8, 18, 19, 20, 3, 6, 7, 8, 4, 6, 7, 8, 5, 6, 7, 20};
static const casadi_int casadi_s18[26] = {22, 1, 0, 22, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21};
static const casadi_int casadi_s19[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[3] = {0., 1., 0.};
static const casadi_real casadi_c2[3] = {1., 0., 0.};

/* meas_jac:(i0[22],i1[3],i2[12],i3[12])->(o0[28x22,152nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real *w0=w+3, *w1=w+155, *w2=w+183, *w3=w+186, *w4=w+195, *w5=w+204, w6, w7, w8, w9, *w10=w+230, *w11=w+233, *w12=w+236, *w13=w+239, *w14=w+248, w15, *w16=w+258, w17, *w18=w+268, *w19=w+277, *w20=w+286, *w21=w+295, *w22=w+304, *w23=w+328, *w26=w+340, *w27=w+342, *w28=w+344, *w29=w+348, w30, w31, w32, w33, w34, w35, w36, w37, *w38=w+360, *w39=w+372, *w40=w+375, *w41=w+378, *w42=w+381, *w43=w+384, *w44=w+387, *w45=w+396, *w46=w+399, *w47=w+402, *w48=w+405, *w49=w+408, *w50=w+428, *w51=w+444;
  /* #0: @0 = zeros(22x28,152nz) */
  casadi_clear(w0, 152);
  /* #1: @1 = zeros(28x1) */
  casadi_clear(w1, 28);
  /* #2: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #3: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #4: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #5: @5 = input[0][0] */
  casadi_copy(arg[0], 22, w5);
  /* #6: @6 = @5[8] */
  for (rr=(&w6), ss=w5+8; ss!=w5+9; ss+=1) *rr++ = *ss;
  /* #7: @7 = cos(@6) */
  w7 = cos( w6 );
  /* #8: @8 = sin(@6) */
  w8 = sin( w6 );
  /* #9: @8 = (-@8) */
  w8 = (- w8 );
  /* #10: @9 = 0 */
  w9 = 0.;
  /* #11: @10 = horzcat(@7, @8, @9) */
  rr=w10;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #12: @10 = @10' */
  /* #13: @7 = sin(@6) */
  w7 = sin( w6 );
  /* #14: @8 = cos(@6) */
  w8 = cos( w6 );
  /* #15: @9 = 0 */
  w9 = 0.;
  /* #16: @11 = horzcat(@7, @8, @9) */
  rr=w11;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #17: @11 = @11' */
  /* #18: @12 = [[0, 0, 1]] */
  casadi_copy(casadi_c0, 3, w12);
  /* #19: @12 = @12' */
  /* #20: @13 = horzcat(@10, @11, @12) */
  rr=w13;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  /* #21: @14 = @13' */
  for (i=0, rr=w14, cs=w13; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #22: @7 = @5[7] */
  for (rr=(&w7), ss=w5+7; ss!=w5+8; ss+=1) *rr++ = *ss;
  /* #23: @8 = cos(@7) */
  w8 = cos( w7 );
  /* #24: @9 = 0 */
  w9 = 0.;
  /* #25: @15 = sin(@7) */
  w15 = sin( w7 );
  /* #26: @10 = horzcat(@8, @9, @15) */
  rr=w10;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w15;
  /* #27: @10 = @10' */
  /* #28: @11 = [[0, 1, 0]] */
  casadi_copy(casadi_c1, 3, w11);
  /* #29: @11 = @11' */
  /* #30: @8 = sin(@7) */
  w8 = sin( w7 );
  /* #31: @8 = (-@8) */
  w8 = (- w8 );
  /* #32: @9 = 0 */
  w9 = 0.;
  /* #33: @15 = cos(@7) */
  w15 = cos( w7 );
  /* #34: @12 = horzcat(@8, @9, @15) */
  rr=w12;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w15;
  /* #35: @12 = @12' */
  /* #36: @13 = horzcat(@10, @11, @12) */
  rr=w13;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  /* #37: @16 = @13' */
  for (i=0, rr=w16, cs=w13; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #38: @4 = mac(@14,@16,@4) */
  for (i=0, rr=w4; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w14+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #39: @10 = [[1, 0, 0]] */
  casadi_copy(casadi_c2, 3, w10);
  /* #40: @10 = @10' */
  /* #41: @8 = 0 */
  w8 = 0.;
  /* #42: @9 = @5[6] */
  for (rr=(&w9), ss=w5+6; ss!=w5+7; ss+=1) *rr++ = *ss;
  /* #43: @15 = cos(@9) */
  w15 = cos( w9 );
  /* #44: @17 = sin(@9) */
  w17 = sin( w9 );
  /* #45: @17 = (-@17) */
  w17 = (- w17 );
  /* #46: @11 = horzcat(@8, @15, @17) */
  rr=w11;
  *rr++ = w8;
  *rr++ = w15;
  *rr++ = w17;
  /* #47: @11 = @11' */
  /* #48: @8 = 0 */
  w8 = 0.;
  /* #49: @15 = sin(@9) */
  w15 = sin( w9 );
  /* #50: @17 = cos(@9) */
  w17 = cos( w9 );
  /* #51: @12 = horzcat(@8, @15, @17) */
  rr=w12;
  *rr++ = w8;
  *rr++ = w15;
  *rr++ = w17;
  /* #52: @12 = @12' */
  /* #53: @13 = horzcat(@10, @11, @12) */
  rr=w13;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  /* #54: @18 = @13' */
  for (i=0, rr=w18, cs=w13; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #55: @3 = mac(@4,@18,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #56: @13 = @3' */
  for (i=0, rr=w13, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #57: @8 = all_-1(3x1,1nz) */
  w8 = -1.;
  /* #58: @2 = mac(@13,@8,@2) */
  casadi_mtimes(w13, casadi_s2, (&w8), casadi_s1, w2, casadi_s0, w, 0);
  /* #59: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #60: @2 = @2' */
  /* #61: (@1[:3] += @2) */
  for (rr=w1+0, ss=w2; rr!=w1+3; rr+=1) *rr += *ss++;
  /* #62: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #63: (@1[3:6] = @2) */
  for (rr=w1+3, ss=w2; rr!=w1+6; rr+=1) *rr = *ss++;
  /* #64: @2 = ones(1x3) */
  casadi_fill(w2, 3, 1.);
  /* #65: (@1[3:6] += @2) */
  for (rr=w1+3, ss=w2; rr!=w1+6; rr+=1) *rr += *ss++;
  /* #66: @8 = 0 */
  w8 = 0.;
  /* #67: (@1[6] = @8) */
  for (rr=w1+6, ss=(&w8); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #68: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #69: (@1[7:10] = @2) */
  for (rr=w1+7, ss=w2; rr!=w1+10; rr+=1) *rr = *ss++;
  /* #70: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #71: @19 = @3' */
  for (i=0, rr=w19, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #72: @8 = all_-1(3x1,1nz) */
  w8 = -1.;
  /* #73: @2 = mac(@19,@8,@2) */
  casadi_mtimes(w19, casadi_s2, (&w8), casadi_s1, w2, casadi_s0, w, 0);
  /* #74: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #75: @2 = @2' */
  /* #76: (@1[7:10] += @2) */
  for (rr=w1+7, ss=w2; rr!=w1+10; rr+=1) *rr += *ss++;
  /* #77: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #78: (@1[10:13] = @2) */
  for (rr=w1+10, ss=w2; rr!=w1+13; rr+=1) *rr = *ss++;
  /* #79: @2 = ones(1x3) */
  casadi_fill(w2, 3, 1.);
  /* #80: (@1[10:13] += @2) */
  for (rr=w1+10, ss=w2; rr!=w1+13; rr+=1) *rr += *ss++;
  /* #81: @8 = 0 */
  w8 = 0.;
  /* #82: (@1[13] = @8) */
  for (rr=w1+13, ss=(&w8); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #83: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #84: (@1[14:17] = @2) */
  for (rr=w1+14, ss=w2; rr!=w1+17; rr+=1) *rr = *ss++;
  /* #85: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #86: @20 = @3' */
  for (i=0, rr=w20, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #87: @8 = all_-1(3x1,1nz) */
  w8 = -1.;
  /* #88: @2 = mac(@20,@8,@2) */
  casadi_mtimes(w20, casadi_s2, (&w8), casadi_s1, w2, casadi_s0, w, 0);
  /* #89: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #90: @2 = @2' */
  /* #91: (@1[14:17] += @2) */
  for (rr=w1+14, ss=w2; rr!=w1+17; rr+=1) *rr += *ss++;
  /* #92: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #93: (@1[17:20] = @2) */
  for (rr=w1+17, ss=w2; rr!=w1+20; rr+=1) *rr = *ss++;
  /* #94: @2 = ones(1x3) */
  casadi_fill(w2, 3, 1.);
  /* #95: (@1[17:20] += @2) */
  for (rr=w1+17, ss=w2; rr!=w1+20; rr+=1) *rr += *ss++;
  /* #96: @8 = 0 */
  w8 = 0.;
  /* #97: (@1[20] = @8) */
  for (rr=w1+20, ss=(&w8); rr!=w1+21; rr+=1) *rr = *ss++;
  /* #98: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #99: (@1[21:24] = @2) */
  for (rr=w1+21, ss=w2; rr!=w1+24; rr+=1) *rr = *ss++;
  /* #100: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #101: @21 = @3' */
  for (i=0, rr=w21, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #102: @8 = all_-1(3x1,1nz) */
  w8 = -1.;
  /* #103: @2 = mac(@21,@8,@2) */
  casadi_mtimes(w21, casadi_s2, (&w8), casadi_s1, w2, casadi_s0, w, 0);
  /* #104: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #105: @2 = @2' */
  /* #106: (@1[21:24] += @2) */
  for (rr=w1+21, ss=w2; rr!=w1+24; rr+=1) *rr += *ss++;
  /* #107: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #108: (@1[24:27] = @2) */
  for (rr=w1+24, ss=w2; rr!=w1+27; rr+=1) *rr = *ss++;
  /* #109: @2 = ones(1x3) */
  casadi_fill(w2, 3, 1.);
  /* #110: (@1[24:27] += @2) */
  for (rr=w1+24, ss=w2; rr!=w1+27; rr+=1) *rr += *ss++;
  /* #111: @8 = 0 */
  w8 = 0.;
  /* #112: (@1[27] = @8) */
  for (rr=w1+27, ss=(&w8); rr!=w1+28; rr+=1) *rr = *ss++;
  /* #113: @22 = @1[:28:7;:6] */
  for (rr=w22, ss=w1+0; ss!=w1+28; ss+=7) for (tt=ss+0; tt!=ss+6; tt+=1) *rr++ = *tt;
  /* #114: (@0[0, 8, 17, 26, 30, 34, 38, 46, 55, 64, 68, 72, 76, 84, 93, 102, 106, 110, 114, 122, 131, 140, 144, 148] = @22) */
  for (cii=casadi_s3, rr=w0, ss=w22; cii!=casadi_s3+24; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #115: @1 = zeros(28x1) */
  casadi_clear(w1, 28);
  /* #116: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #117: @8 = all_-1(3x1,1nz) */
  w8 = -1.;
  /* #118: @2 = mac(@13,@8,@2) */
  casadi_mtimes(w13, casadi_s2, (&w8), casadi_s4, w2, casadi_s0, w, 0);
  /* #119: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #120: @2 = @2' */
  /* #121: (@1[:3] += @2) */
  for (rr=w1+0, ss=w2; rr!=w1+3; rr+=1) *rr += *ss++;
  /* #122: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #123: (@1[3:6] = @2) */
  for (rr=w1+3, ss=w2; rr!=w1+6; rr+=1) *rr = *ss++;
  /* #124: @8 = 0 */
  w8 = 0.;
  /* #125: (@1[6] = @8) */
  for (rr=w1+6, ss=(&w8); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #126: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #127: (@1[7:10] = @2) */
  for (rr=w1+7, ss=w2; rr!=w1+10; rr+=1) *rr = *ss++;
  /* #128: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #129: @8 = all_-1(3x1,1nz) */
  w8 = -1.;
  /* #130: @2 = mac(@19,@8,@2) */
  casadi_mtimes(w19, casadi_s2, (&w8), casadi_s4, w2, casadi_s0, w, 0);
  /* #131: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #132: @2 = @2' */
  /* #133: (@1[7:10] += @2) */
  for (rr=w1+7, ss=w2; rr!=w1+10; rr+=1) *rr += *ss++;
  /* #134: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #135: (@1[10:13] = @2) */
  for (rr=w1+10, ss=w2; rr!=w1+13; rr+=1) *rr = *ss++;
  /* #136: @8 = 0 */
  w8 = 0.;
  /* #137: (@1[13] = @8) */
  for (rr=w1+13, ss=(&w8); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #138: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #139: (@1[14:17] = @2) */
  for (rr=w1+14, ss=w2; rr!=w1+17; rr+=1) *rr = *ss++;
  /* #140: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #141: @8 = all_-1(3x1,1nz) */
  w8 = -1.;
  /* #142: @2 = mac(@20,@8,@2) */
  casadi_mtimes(w20, casadi_s2, (&w8), casadi_s4, w2, casadi_s0, w, 0);
  /* #143: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #144: @2 = @2' */
  /* #145: (@1[14:17] += @2) */
  for (rr=w1+14, ss=w2; rr!=w1+17; rr+=1) *rr += *ss++;
  /* #146: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #147: (@1[17:20] = @2) */
  for (rr=w1+17, ss=w2; rr!=w1+20; rr+=1) *rr = *ss++;
  /* #148: @8 = 0 */
  w8 = 0.;
  /* #149: (@1[20] = @8) */
  for (rr=w1+20, ss=(&w8); rr!=w1+21; rr+=1) *rr = *ss++;
  /* #150: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #151: (@1[21:24] = @2) */
  for (rr=w1+21, ss=w2; rr!=w1+24; rr+=1) *rr = *ss++;
  /* #152: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #153: @8 = all_-1(3x1,1nz) */
  w8 = -1.;
  /* #154: @2 = mac(@21,@8,@2) */
  casadi_mtimes(w21, casadi_s2, (&w8), casadi_s4, w2, casadi_s0, w, 0);
  /* #155: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #156: @2 = @2' */
  /* #157: (@1[21:24] += @2) */
  for (rr=w1+21, ss=w2; rr!=w1+24; rr+=1) *rr += *ss++;
  /* #158: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #159: (@1[24:27] = @2) */
  for (rr=w1+24, ss=w2; rr!=w1+27; rr+=1) *rr = *ss++;
  /* #160: @8 = 0 */
  w8 = 0.;
  /* #161: (@1[27] = @8) */
  for (rr=w1+27, ss=(&w8); rr!=w1+28; rr+=1) *rr = *ss++;
  /* #162: @23 = @1[:28:7;:3] */
  for (rr=w23, ss=w1+0; ss!=w1+28; ss+=7) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #163: (@0[1, 9, 18, 39, 47, 56, 77, 85, 94, 115, 123, 132] = @23) */
  for (cii=casadi_s5, rr=w0, ss=w23; cii!=casadi_s5+12; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #164: @1 = zeros(28x1) */
  casadi_clear(w1, 28);
  /* #165: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #166: @8 = all_-1(3x1,1nz) */
  w8 = -1.;
  /* #167: @2 = mac(@13,@8,@2) */
  casadi_mtimes(w13, casadi_s2, (&w8), casadi_s6, w2, casadi_s0, w, 0);
  /* #168: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #169: @2 = @2' */
  /* #170: (@1[:3] += @2) */
  for (rr=w1+0, ss=w2; rr!=w1+3; rr+=1) *rr += *ss++;
  /* #171: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #172: (@1[3:6] = @2) */
  for (rr=w1+3, ss=w2; rr!=w1+6; rr+=1) *rr = *ss++;
  /* #173: @8 = 0 */
  w8 = 0.;
  /* #174: (@1[6] = @8) */
  for (rr=w1+6, ss=(&w8); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #175: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #176: (@1[7:10] = @2) */
  for (rr=w1+7, ss=w2; rr!=w1+10; rr+=1) *rr = *ss++;
  /* #177: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #178: @8 = all_-1(3x1,1nz) */
  w8 = -1.;
  /* #179: @2 = mac(@19,@8,@2) */
  casadi_mtimes(w19, casadi_s2, (&w8), casadi_s6, w2, casadi_s0, w, 0);
  /* #180: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #181: @2 = @2' */
  /* #182: (@1[7:10] += @2) */
  for (rr=w1+7, ss=w2; rr!=w1+10; rr+=1) *rr += *ss++;
  /* #183: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #184: (@1[10:13] = @2) */
  for (rr=w1+10, ss=w2; rr!=w1+13; rr+=1) *rr = *ss++;
  /* #185: @8 = 0 */
  w8 = 0.;
  /* #186: (@1[13] = @8) */
  for (rr=w1+13, ss=(&w8); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #187: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #188: (@1[14:17] = @2) */
  for (rr=w1+14, ss=w2; rr!=w1+17; rr+=1) *rr = *ss++;
  /* #189: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #190: @8 = all_-1(3x1,1nz) */
  w8 = -1.;
  /* #191: @2 = mac(@20,@8,@2) */
  casadi_mtimes(w20, casadi_s2, (&w8), casadi_s6, w2, casadi_s0, w, 0);
  /* #192: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #193: @2 = @2' */
  /* #194: (@1[14:17] += @2) */
  for (rr=w1+14, ss=w2; rr!=w1+17; rr+=1) *rr += *ss++;
  /* #195: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #196: (@1[17:20] = @2) */
  for (rr=w1+17, ss=w2; rr!=w1+20; rr+=1) *rr = *ss++;
  /* #197: @8 = 0 */
  w8 = 0.;
  /* #198: (@1[20] = @8) */
  for (rr=w1+20, ss=(&w8); rr!=w1+21; rr+=1) *rr = *ss++;
  /* #199: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #200: (@1[21:24] = @2) */
  for (rr=w1+21, ss=w2; rr!=w1+24; rr+=1) *rr = *ss++;
  /* #201: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #202: @8 = all_-1(3x1,1nz) */
  w8 = -1.;
  /* #203: @2 = mac(@21,@8,@2) */
  casadi_mtimes(w21, casadi_s2, (&w8), casadi_s6, w2, casadi_s0, w, 0);
  /* #204: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #205: @2 = @2' */
  /* #206: (@1[21:24] += @2) */
  for (rr=w1+21, ss=w2; rr!=w1+24; rr+=1) *rr += *ss++;
  /* #207: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #208: (@1[24:27] = @2) */
  for (rr=w1+24, ss=w2; rr!=w1+27; rr+=1) *rr = *ss++;
  /* #209: @8 = 0 */
  w8 = 0.;
  /* #210: (@1[27] = @8) */
  for (rr=w1+27, ss=(&w8); rr!=w1+28; rr+=1) *rr = *ss++;
  /* #211: @23 = @1[:28:7;:3] */
  for (rr=w23, ss=w1+0; ss!=w1+28; ss+=7) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #212: (@0[2, 10, 19, 40, 48, 57, 78, 86, 95, 116, 124, 133] = @23) */
  for (cii=casadi_s7, rr=w0, ss=w23; cii!=casadi_s7+12; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #213: @1 = zeros(28x1) */
  casadi_clear(w1, 28);
  /* #214: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #215: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #216: @24 = zeros(3x1,0nz) */
  /* #217: @25 = 00 */
  /* #218: @8 = sin(@9) */
  w8 = sin( w9 );
  /* #219: @8 = (-@8) */
  w8 = (- w8 );
  /* #220: @15 = cos(@9) */
  w15 = cos( w9 );
  /* #221: @15 = (-@15) */
  w15 = (- w15 );
  /* #222: @26 = horzcat(@25, @8, @15) */
  rr=w26;
  *rr++ = w8;
  *rr++ = w15;
  /* #223: @26 = @26' */
  /* #224: @25 = 00 */
  /* #225: @8 = cos(@9) */
  w8 = cos( w9 );
  /* #226: @9 = sin(@9) */
  w9 = sin( w9 );
  /* #227: @9 = (-@9) */
  w9 = (- w9 );
  /* #228: @27 = horzcat(@25, @8, @9) */
  rr=w27;
  *rr++ = w8;
  *rr++ = w9;
  /* #229: @27 = @27' */
  /* #230: @28 = horzcat(@24, @26, @27) */
  rr=w28;
  for (i=0, cs=w26; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  /* #231: @29 = @28' */
  casadi_trans(w28,casadi_s8, w29, casadi_s8, iw);
  /* #232: @3 = mac(@4,@29,@3) */
  casadi_mtimes(w4, casadi_s2, w29, casadi_s8, w3, casadi_s2, w, 0);
  /* #233: @4 = @3' */
  for (i=0, rr=w4, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #234: @10 = @5[9:12] */
  for (rr=w10, ss=w5+9; ss!=w5+12; ss+=1) *rr++ = *ss;
  /* #235: @11 = @5[:3] */
  for (rr=w11, ss=w5+0; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #236: @10 = (@10-@11) */
  for (i=0, rr=w10, cs=w11; i<3; ++i) (*rr++) -= (*cs++);
  /* #237: @2 = mac(@4,@10,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w10+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #238: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #239: @2 = @2' */
  /* #240: (@1[:3] += @2) */
  for (rr=w1+0, ss=w2; rr!=w1+3; rr+=1) *rr += *ss++;
  /* #241: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #242: (@1[3:6] = @2) */
  for (rr=w1+3, ss=w2; rr!=w1+6; rr+=1) *rr = *ss++;
  /* #243: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #244: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #245: @8 = 0 */
  w8 = 0.;
  /* #246: @9 = -0.0838 */
  w9 = -8.3799999999999999e-02;
  /* #247: @23 = input[2][0] */
  casadi_copy(arg[2], 12, w23);
  /* #248: @15 = @23[0] */
  for (rr=(&w15), ss=w23+0; ss!=w23+1; ss+=1) *rr++ = *ss;
  /* #249: @17 = sin(@15) */
  w17 = sin( w15 );
  /* #250: @9 = (@9*@17) */
  w9 *= w17;
  /* #251: @30 = 0.2 */
  w30 = 2.0000000000000001e-01;
  /* #252: @15 = cos(@15) */
  w15 = cos( w15 );
  /* #253: @30 = (@30*@15) */
  w30 *= w15;
  /* #254: @31 = @23[1] */
  for (rr=(&w31), ss=w23+1; ss!=w23+2; ss+=1) *rr++ = *ss;
  /* #255: @32 = cos(@31) */
  w32 = cos( w31 );
  /* #256: @30 = (@30*@32) */
  w30 *= w32;
  /* #257: @9 = (@9+@30) */
  w9 += w30;
  /* #258: @30 = 0.2 */
  w30 = 2.0000000000000001e-01;
  /* #259: @30 = (@30*@15) */
  w30 *= w15;
  /* #260: @30 = (@30*@32) */
  w30 *= w32;
  /* #261: @33 = @23[2] */
  for (rr=(&w33), ss=w23+2; ss!=w23+3; ss+=1) *rr++ = *ss;
  /* #262: @34 = cos(@33) */
  w34 = cos( w33 );
  /* #263: @30 = (@30*@34) */
  w30 *= w34;
  /* #264: @9 = (@9+@30) */
  w9 += w30;
  /* #265: @30 = 0.2 */
  w30 = 2.0000000000000001e-01;
  /* #266: @30 = (@30*@15) */
  w30 *= w15;
  /* #267: @35 = sin(@31) */
  w35 = sin( w31 );
  /* #268: @30 = (@30*@35) */
  w30 *= w35;
  /* #269: @36 = sin(@33) */
  w36 = sin( w33 );
  /* #270: @30 = (@30*@36) */
  w30 *= w36;
  /* #271: @9 = (@9-@30) */
  w9 -= w30;
  /* #272: @30 = 0.0838 */
  w30 = 8.3799999999999999e-02;
  /* #273: @30 = (@30*@15) */
  w30 *= w15;
  /* #274: @37 = 0.2 */
  w37 = 2.0000000000000001e-01;
  /* #275: @37 = (@37*@32) */
  w37 *= w32;
  /* #276: @37 = (@37*@17) */
  w37 *= w17;
  /* #277: @30 = (@30+@37) */
  w30 += w37;
  /* #278: @37 = 0.2 */
  w37 = 2.0000000000000001e-01;
  /* #279: @37 = (@37*@32) */
  w37 *= w32;
  /* #280: @37 = (@37*@34) */
  w37 *= w34;
  /* #281: @37 = (@37*@17) */
  w37 *= w17;
  /* #282: @30 = (@30+@37) */
  w30 += w37;
  /* #283: @37 = 0.2 */
  w37 = 2.0000000000000001e-01;
  /* #284: @37 = (@37*@17) */
  w37 *= w17;
  /* #285: @37 = (@37*@35) */
  w37 *= w35;
  /* #286: @37 = (@37*@36) */
  w37 *= w36;
  /* #287: @30 = (@30-@37) */
  w30 -= w37;
  /* #288: @37 = 0.2 */
  w37 = 2.0000000000000001e-01;
  /* #289: @31 = (@31+@33) */
  w31 += w33;
  /* #290: @33 = cos(@31) */
  w33 = cos( w31 );
  /* #291: @37 = (@37*@33) */
  w37 *= w33;
  /* #292: @37 = (-@37) */
  w37 = (- w37 );
  /* #293: @33 = 0.2 */
  w33 = 2.0000000000000001e-01;
  /* #294: @33 = (@33*@32) */
  w33 *= w32;
  /* #295: @33 = (@37-@33) */
  w33  = (w37-w33);
  /* #296: @32 = 0.2 */
  w32 = 2.0000000000000001e-01;
  /* #297: @32 = (@32*@35) */
  w32 *= w35;
  /* #298: @35 = 0.2 */
  w35 = 2.0000000000000001e-01;
  /* #299: @31 = sin(@31) */
  w31 = sin( w31 );
  /* #300: @35 = (@35*@31) */
  w35 *= w31;
  /* #301: @32 = (@32+@35) */
  w32 += w35;
  /* #302: @31 = (@17*@32) */
  w31  = (w17*w32);
  /* #303: @31 = (-@31) */
  w31 = (- w31 );
  /* #304: @32 = (@15*@32) */
  w32  = (w15*w32);
  /* #305: @17 = (@17*@35) */
  w17 *= w35;
  /* #306: @17 = (-@17) */
  w17 = (- w17 );
  /* #307: @15 = (@15*@35) */
  w15 *= w35;
  /* #308: @4 = horzcat(@8, @9, @30, @33, @31, @32, @37, @17, @15) */
  rr=w4;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w30;
  *rr++ = w33;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w37;
  *rr++ = w17;
  *rr++ = w15;
  /* #309: @4 = reshape(@4) */
  /* #310: @4 = (-@4) */
  for (i=0, rr=w4, cs=w4; i<9; ++i) *rr++ = (- *cs++ );
  /* #311: @38 = input[3][0] */
  casadi_copy(arg[3], 12, w38);
  /* #312: @39 = @38[:3] */
  for (rr=w39, ss=w38+0; ss!=w38+3; ss+=1) *rr++ = *ss;
  /* #313: @12 = mac(@4,@39,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w39+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #314: @39 = zeros(3x1) */
  casadi_clear(w39, 3);
  /* #315: @8 = 0 */
  w8 = 0.;
  /* #316: @40 = input[1][0] */
  casadi_copy(arg[1], 3, w40);
  /* #317: @9 = @40[2] */
  for (rr=(&w9), ss=w40+2; ss!=w40+3; ss+=1) *rr++ = *ss;
  /* #318: @30 = (-@9) */
  w30 = (- w9 );
  /* #319: @33 = @40[1] */
  for (rr=(&w33), ss=w40+1; ss!=w40+2; ss+=1) *rr++ = *ss;
  /* #320: @41 = horzcat(@8, @30, @33) */
  rr=w41;
  *rr++ = w8;
  *rr++ = w30;
  *rr++ = w33;
  /* #321: @41 = @41' */
  /* #322: @8 = 0 */
  w8 = 0.;
  /* #323: @30 = @40[0] */
  for (rr=(&w30), ss=w40+0; ss!=w40+1; ss+=1) *rr++ = *ss;
  /* #324: @31 = (-@30) */
  w31 = (- w30 );
  /* #325: @42 = horzcat(@9, @8, @31) */
  rr=w42;
  *rr++ = w9;
  *rr++ = w8;
  *rr++ = w31;
  /* #326: @42 = @42' */
  /* #327: @33 = (-@33) */
  w33 = (- w33 );
  /* #328: @9 = 0 */
  w9 = 0.;
  /* #329: @43 = horzcat(@33, @30, @9) */
  rr=w43;
  *rr++ = w33;
  *rr++ = w30;
  *rr++ = w9;
  /* #330: @43 = @43' */
  /* #331: @4 = horzcat(@41, @42, @43) */
  rr=w4;
  for (i=0, cs=w41; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<3; ++i) *rr++ = *cs++;
  /* #332: @44 = @4' */
  for (i=0, rr=w44, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #333: @33 = 0.1805 */
  w33 = 1.8049999999999999e-01;
  /* #334: @30 = 0.2 */
  w30 = 2.0000000000000001e-01;
  /* #335: @9 = @23[1] */
  for (rr=(&w9), ss=w23+1; ss!=w23+2; ss+=1) *rr++ = *ss;
  /* #336: @8 = sin(@9) */
  w8 = sin( w9 );
  /* #337: @30 = (@30*@8) */
  w30 *= w8;
  /* #338: @33 = (@33-@30) */
  w33 -= w30;
  /* #339: @30 = 0.2 */
  w30 = 2.0000000000000001e-01;
  /* #340: @31 = @23[2] */
  for (rr=(&w31), ss=w23+2; ss!=w23+3; ss+=1) *rr++ = *ss;
  /* #341: @32 = (@9+@31) */
  w32  = (w9+w31);
  /* #342: @32 = sin(@32) */
  w32 = sin( w32 );
  /* #343: @30 = (@30*@32) */
  w30 *= w32;
  /* #344: @33 = (@33-@30) */
  w33 -= w30;
  /* #345: @30 = 0.047 */
  w30 = 4.7000000000000000e-02;
  /* #346: @32 = 0.0838 */
  w32 = 8.3799999999999999e-02;
  /* #347: @37 = @23[0] */
  for (rr=(&w37), ss=w23+0; ss!=w23+1; ss+=1) *rr++ = *ss;
  /* #348: @17 = cos(@37) */
  w17 = cos( w37 );
  /* #349: @32 = (@32*@17) */
  w32 *= w17;
  /* #350: @30 = (@30+@32) */
  w30 += w32;
  /* #351: @32 = 0.2 */
  w32 = 2.0000000000000001e-01;
  /* #352: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #353: @32 = (@32*@9) */
  w32 *= w9;
  /* #354: @37 = sin(@37) */
  w37 = sin( w37 );
  /* #355: @32 = (@32*@37) */
  w32 *= w37;
  /* #356: @30 = (@30+@32) */
  w30 += w32;
  /* #357: @32 = 0.2 */
  w32 = 2.0000000000000001e-01;
  /* #358: @32 = (@32*@9) */
  w32 *= w9;
  /* #359: @15 = cos(@31) */
  w15 = cos( w31 );
  /* #360: @32 = (@32*@15) */
  w32 *= w15;
  /* #361: @32 = (@32*@37) */
  w32 *= w37;
  /* #362: @30 = (@30+@32) */
  w30 += w32;
  /* #363: @32 = 0.2 */
  w32 = 2.0000000000000001e-01;
  /* #364: @32 = (@32*@37) */
  w32 *= w37;
  /* #365: @32 = (@32*@8) */
  w32 *= w8;
  /* #366: @31 = sin(@31) */
  w31 = sin( w31 );
  /* #367: @32 = (@32*@31) */
  w32 *= w31;
  /* #368: @30 = (@30-@32) */
  w30 -= w32;
  /* #369: @32 = 0.0838 */
  w32 = 8.3799999999999999e-02;
  /* #370: @32 = (@32*@37) */
  w32 *= w37;
  /* #371: @37 = 0.2 */
  w37 = 2.0000000000000001e-01;
  /* #372: @37 = (@37*@17) */
  w37 *= w17;
  /* #373: @37 = (@37*@9) */
  w37 *= w9;
  /* #374: @32 = (@32-@37) */
  w32 -= w37;
  /* #375: @37 = 0.2 */
  w37 = 2.0000000000000001e-01;
  /* #376: @37 = (@37*@17) */
  w37 *= w17;
  /* #377: @37 = (@37*@9) */
  w37 *= w9;
  /* #378: @37 = (@37*@15) */
  w37 *= w15;
  /* #379: @32 = (@32-@37) */
  w32 -= w37;
  /* #380: @37 = 0.2 */
  w37 = 2.0000000000000001e-01;
  /* #381: @37 = (@37*@17) */
  w37 *= w17;
  /* #382: @37 = (@37*@8) */
  w37 *= w8;
  /* #383: @37 = (@37*@31) */
  w37 *= w31;
  /* #384: @32 = (@32+@37) */
  w32 += w37;
  /* #385: @41 = vertcat(@33, @30, @32) */
  rr=w41;
  *rr++ = w33;
  *rr++ = w30;
  *rr++ = w32;
  /* #386: @39 = mac(@44,@41,@39) */
  for (i=0, rr=w39; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w44+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #387: @12 = (@12-@39) */
  for (i=0, rr=w12, cs=w39; i<3; ++i) (*rr++) -= (*cs++);
  /* #388: @2 = mac(@3,@12,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #389: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #390: @2 = @2' */
  /* #391: (@1[3:6] += @2) */
  for (rr=w1+3, ss=w2; rr!=w1+6; rr+=1) *rr += *ss++;
  /* #392: @33 = 0 */
  w33 = 0.;
  /* #393: (@1[6] = @33) */
  for (rr=w1+6, ss=(&w33); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #394: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #395: (@1[7:10] = @2) */
  for (rr=w1+7, ss=w2; rr!=w1+10; rr+=1) *rr = *ss++;
  /* #396: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #397: @44 = @3' */
  for (i=0, rr=w44, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #398: @39 = @5[12:15] */
  for (rr=w39, ss=w5+12; ss!=w5+15; ss+=1) *rr++ = *ss;
  /* #399: @39 = (@39-@11) */
  for (i=0, rr=w39, cs=w11; i<3; ++i) (*rr++) -= (*cs++);
  /* #400: @2 = mac(@44,@39,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w44+j, tt=w39+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #401: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #402: @2 = @2' */
  /* #403: (@1[7:10] += @2) */
  for (rr=w1+7, ss=w2; rr!=w1+10; rr+=1) *rr += *ss++;
  /* #404: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #405: (@1[10:13] = @2) */
  for (rr=w1+10, ss=w2; rr!=w1+13; rr+=1) *rr = *ss++;
  /* #406: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #407: @41 = zeros(3x1) */
  casadi_clear(w41, 3);
  /* #408: @33 = 0 */
  w33 = 0.;
  /* #409: @30 = 0.0838 */
  w30 = 8.3799999999999999e-02;
  /* #410: @32 = @23[3] */
  for (rr=(&w32), ss=w23+3; ss!=w23+4; ss+=1) *rr++ = *ss;
  /* #411: @37 = sin(@32) */
  w37 = sin( w32 );
  /* #412: @30 = (@30*@37) */
  w30 *= w37;
  /* #413: @31 = 0.2 */
  w31 = 2.0000000000000001e-01;
  /* #414: @32 = cos(@32) */
  w32 = cos( w32 );
  /* #415: @31 = (@31*@32) */
  w31 *= w32;
  /* #416: @8 = @23[4] */
  for (rr=(&w8), ss=w23+4; ss!=w23+5; ss+=1) *rr++ = *ss;
  /* #417: @17 = cos(@8) */
  w17 = cos( w8 );
  /* #418: @31 = (@31*@17) */
  w31 *= w17;
  /* #419: @30 = (@30+@31) */
  w30 += w31;
  /* #420: @31 = 0.2 */
  w31 = 2.0000000000000001e-01;
  /* #421: @31 = (@31*@32) */
  w31 *= w32;
  /* #422: @31 = (@31*@17) */
  w31 *= w17;
  /* #423: @15 = @23[5] */
  for (rr=(&w15), ss=w23+5; ss!=w23+6; ss+=1) *rr++ = *ss;
  /* #424: @9 = cos(@15) */
  w9 = cos( w15 );
  /* #425: @31 = (@31*@9) */
  w31 *= w9;
  /* #426: @30 = (@30+@31) */
  w30 += w31;
  /* #427: @31 = 0.2 */
  w31 = 2.0000000000000001e-01;
  /* #428: @31 = (@31*@32) */
  w31 *= w32;
  /* #429: @35 = sin(@8) */
  w35 = sin( w8 );
  /* #430: @31 = (@31*@35) */
  w31 *= w35;
  /* #431: @36 = sin(@15) */
  w36 = sin( w15 );
  /* #432: @31 = (@31*@36) */
  w31 *= w36;
  /* #433: @30 = (@30-@31) */
  w30 -= w31;
  /* #434: @31 = -0.0838 */
  w31 = -8.3799999999999999e-02;
  /* #435: @31 = (@31*@32) */
  w31 *= w32;
  /* #436: @34 = 0.2 */
  w34 = 2.0000000000000001e-01;
  /* #437: @34 = (@34*@17) */
  w34 *= w17;
  /* #438: @34 = (@34*@37) */
  w34 *= w37;
  /* #439: @31 = (@31+@34) */
  w31 += w34;
  /* #440: @34 = 0.2 */
  w34 = 2.0000000000000001e-01;
  /* #441: @34 = (@34*@17) */
  w34 *= w17;
  /* #442: @34 = (@34*@9) */
  w34 *= w9;
  /* #443: @34 = (@34*@37) */
  w34 *= w37;
  /* #444: @31 = (@31+@34) */
  w31 += w34;
  /* #445: @34 = 0.2 */
  w34 = 2.0000000000000001e-01;
  /* #446: @34 = (@34*@37) */
  w34 *= w37;
  /* #447: @34 = (@34*@35) */
  w34 *= w35;
  /* #448: @34 = (@34*@36) */
  w34 *= w36;
  /* #449: @31 = (@31-@34) */
  w31 -= w34;
  /* #450: @34 = 0.2 */
  w34 = 2.0000000000000001e-01;
  /* #451: @8 = (@8+@15) */
  w8 += w15;
  /* #452: @15 = cos(@8) */
  w15 = cos( w8 );
  /* #453: @34 = (@34*@15) */
  w34 *= w15;
  /* #454: @34 = (-@34) */
  w34 = (- w34 );
  /* #455: @15 = 0.2 */
  w15 = 2.0000000000000001e-01;
  /* #456: @15 = (@15*@17) */
  w15 *= w17;
  /* #457: @15 = (@34-@15) */
  w15  = (w34-w15);
  /* #458: @17 = 0.2 */
  w17 = 2.0000000000000001e-01;
  /* #459: @17 = (@17*@35) */
  w17 *= w35;
  /* #460: @35 = 0.2 */
  w35 = 2.0000000000000001e-01;
  /* #461: @8 = sin(@8) */
  w8 = sin( w8 );
  /* #462: @35 = (@35*@8) */
  w35 *= w8;
  /* #463: @17 = (@17+@35) */
  w17 += w35;
  /* #464: @8 = (@37*@17) */
  w8  = (w37*w17);
  /* #465: @8 = (-@8) */
  w8 = (- w8 );
  /* #466: @17 = (@32*@17) */
  w17  = (w32*w17);
  /* #467: @37 = (@37*@35) */
  w37 *= w35;
  /* #468: @37 = (-@37) */
  w37 = (- w37 );
  /* #469: @32 = (@32*@35) */
  w32 *= w35;
  /* #470: @44 = horzcat(@33, @30, @31, @15, @8, @17, @34, @37, @32) */
  rr=w44;
  *rr++ = w33;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w15;
  *rr++ = w8;
  *rr++ = w17;
  *rr++ = w34;
  *rr++ = w37;
  *rr++ = w32;
  /* #471: @44 = reshape(@44) */
  /* #472: @44 = (-@44) */
  for (i=0, rr=w44, cs=w44; i<9; ++i) *rr++ = (- *cs++ );
  /* #473: @42 = @38[3:6] */
  for (rr=w42, ss=w38+3; ss!=w38+6; ss+=1) *rr++ = *ss;
  /* #474: @41 = mac(@44,@42,@41) */
  for (i=0, rr=w41; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w44+j, tt=w42+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #475: @42 = zeros(3x1) */
  casadi_clear(w42, 3);
  /* #476: @33 = 0 */
  w33 = 0.;
  /* #477: @30 = @40[2] */
  for (rr=(&w30), ss=w40+2; ss!=w40+3; ss+=1) *rr++ = *ss;
  /* #478: @31 = (-@30) */
  w31 = (- w30 );
  /* #479: @15 = @40[1] */
  for (rr=(&w15), ss=w40+1; ss!=w40+2; ss+=1) *rr++ = *ss;
  /* #480: @43 = horzcat(@33, @31, @15) */
  rr=w43;
  *rr++ = w33;
  *rr++ = w31;
  *rr++ = w15;
  /* #481: @43 = @43' */
  /* #482: @33 = 0 */
  w33 = 0.;
  /* #483: @31 = @40[0] */
  for (rr=(&w31), ss=w40+0; ss!=w40+1; ss+=1) *rr++ = *ss;
  /* #484: @8 = (-@31) */
  w8 = (- w31 );
  /* #485: @45 = horzcat(@30, @33, @8) */
  rr=w45;
  *rr++ = w30;
  *rr++ = w33;
  *rr++ = w8;
  /* #486: @45 = @45' */
  /* #487: @15 = (-@15) */
  w15 = (- w15 );
  /* #488: @30 = 0 */
  w30 = 0.;
  /* #489: @46 = horzcat(@15, @31, @30) */
  rr=w46;
  *rr++ = w15;
  *rr++ = w31;
  *rr++ = w30;
  /* #490: @46 = @46' */
  /* #491: @44 = horzcat(@43, @45, @46) */
  rr=w44;
  for (i=0, cs=w43; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  /* #492: @4 = @44' */
  for (i=0, rr=w4, cs=w44; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #493: @15 = 0.1805 */
  w15 = 1.8049999999999999e-01;
  /* #494: @31 = 0.2 */
  w31 = 2.0000000000000001e-01;
  /* #495: @30 = @23[4] */
  for (rr=(&w30), ss=w23+4; ss!=w23+5; ss+=1) *rr++ = *ss;
  /* #496: @33 = sin(@30) */
  w33 = sin( w30 );
  /* #497: @31 = (@31*@33) */
  w31 *= w33;
  /* #498: @15 = (@15-@31) */
  w15 -= w31;
  /* #499: @31 = 0.2 */
  w31 = 2.0000000000000001e-01;
  /* #500: @8 = @23[5] */
  for (rr=(&w8), ss=w23+5; ss!=w23+6; ss+=1) *rr++ = *ss;
  /* #501: @17 = (@30+@8) */
  w17  = (w30+w8);
  /* #502: @17 = sin(@17) */
  w17 = sin( w17 );
  /* #503: @31 = (@31*@17) */
  w31 *= w17;
  /* #504: @15 = (@15-@31) */
  w15 -= w31;
  /* #505: @31 = -0.047 */
  w31 = -4.7000000000000000e-02;
  /* #506: @17 = -0.0838 */
  w17 = -8.3799999999999999e-02;
  /* #507: @34 = @23[3] */
  for (rr=(&w34), ss=w23+3; ss!=w23+4; ss+=1) *rr++ = *ss;
  /* #508: @37 = cos(@34) */
  w37 = cos( w34 );
  /* #509: @17 = (@17*@37) */
  w17 *= w37;
  /* #510: @31 = (@31+@17) */
  w31 += w17;
  /* #511: @17 = 0.2 */
  w17 = 2.0000000000000001e-01;
  /* #512: @30 = cos(@30) */
  w30 = cos( w30 );
  /* #513: @17 = (@17*@30) */
  w17 *= w30;
  /* #514: @34 = sin(@34) */
  w34 = sin( w34 );
  /* #515: @17 = (@17*@34) */
  w17 *= w34;
  /* #516: @31 = (@31+@17) */
  w31 += w17;
  /* #517: @17 = 0.2 */
  w17 = 2.0000000000000001e-01;
  /* #518: @17 = (@17*@30) */
  w17 *= w30;
  /* #519: @32 = cos(@8) */
  w32 = cos( w8 );
  /* #520: @17 = (@17*@32) */
  w17 *= w32;
  /* #521: @17 = (@17*@34) */
  w17 *= w34;
  /* #522: @31 = (@31+@17) */
  w31 += w17;
  /* #523: @17 = 0.2 */
  w17 = 2.0000000000000001e-01;
  /* #524: @17 = (@17*@34) */
  w17 *= w34;
  /* #525: @17 = (@17*@33) */
  w17 *= w33;
  /* #526: @8 = sin(@8) */
  w8 = sin( w8 );
  /* #527: @17 = (@17*@8) */
  w17 *= w8;
  /* #528: @31 = (@31-@17) */
  w31 -= w17;
  /* #529: @17 = -0.0838 */
  w17 = -8.3799999999999999e-02;
  /* #530: @17 = (@17*@34) */
  w17 *= w34;
  /* #531: @34 = 0.2 */
  w34 = 2.0000000000000001e-01;
  /* #532: @34 = (@34*@37) */
  w34 *= w37;
  /* #533: @34 = (@34*@30) */
  w34 *= w30;
  /* #534: @17 = (@17-@34) */
  w17 -= w34;
  /* #535: @34 = 0.2 */
  w34 = 2.0000000000000001e-01;
  /* #536: @34 = (@34*@37) */
  w34 *= w37;
  /* #537: @34 = (@34*@30) */
  w34 *= w30;
  /* #538: @34 = (@34*@32) */
  w34 *= w32;
  /* #539: @17 = (@17-@34) */
  w17 -= w34;
  /* #540: @34 = 0.2 */
  w34 = 2.0000000000000001e-01;
  /* #541: @34 = (@34*@37) */
  w34 *= w37;
  /* #542: @34 = (@34*@33) */
  w34 *= w33;
  /* #543: @34 = (@34*@8) */
  w34 *= w8;
  /* #544: @17 = (@17+@34) */
  w17 += w34;
  /* #545: @43 = vertcat(@15, @31, @17) */
  rr=w43;
  *rr++ = w15;
  *rr++ = w31;
  *rr++ = w17;
  /* #546: @42 = mac(@4,@43,@42) */
  for (i=0, rr=w42; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w43+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #547: @41 = (@41-@42) */
  for (i=0, rr=w41, cs=w42; i<3; ++i) (*rr++) -= (*cs++);
  /* #548: @2 = mac(@3,@41,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #549: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #550: @2 = @2' */
  /* #551: (@1[10:13] += @2) */
  for (rr=w1+10, ss=w2; rr!=w1+13; rr+=1) *rr += *ss++;
  /* #552: @15 = 0 */
  w15 = 0.;
  /* #553: (@1[13] = @15) */
  for (rr=w1+13, ss=(&w15); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #554: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #555: (@1[14:17] = @2) */
  for (rr=w1+14, ss=w2; rr!=w1+17; rr+=1) *rr = *ss++;
  /* #556: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #557: @4 = @3' */
  for (i=0, rr=w4, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #558: @42 = @5[15:18] */
  for (rr=w42, ss=w5+15; ss!=w5+18; ss+=1) *rr++ = *ss;
  /* #559: @42 = (@42-@11) */
  for (i=0, rr=w42, cs=w11; i<3; ++i) (*rr++) -= (*cs++);
  /* #560: @2 = mac(@4,@42,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w42+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #561: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #562: @2 = @2' */
  /* #563: (@1[14:17] += @2) */
  for (rr=w1+14, ss=w2; rr!=w1+17; rr+=1) *rr += *ss++;
  /* #564: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #565: (@1[17:20] = @2) */
  for (rr=w1+17, ss=w2; rr!=w1+20; rr+=1) *rr = *ss++;
  /* #566: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #567: @43 = zeros(3x1) */
  casadi_clear(w43, 3);
  /* #568: @15 = 0 */
  w15 = 0.;
  /* #569: @31 = -0.0838 */
  w31 = -8.3799999999999999e-02;
  /* #570: @17 = @23[6] */
  for (rr=(&w17), ss=w23+6; ss!=w23+7; ss+=1) *rr++ = *ss;
  /* #571: @34 = sin(@17) */
  w34 = sin( w17 );
  /* #572: @31 = (@31*@34) */
  w31 *= w34;
  /* #573: @8 = 0.2 */
  w8 = 2.0000000000000001e-01;
  /* #574: @17 = cos(@17) */
  w17 = cos( w17 );
  /* #575: @8 = (@8*@17) */
  w8 *= w17;
  /* #576: @33 = @23[7] */
  for (rr=(&w33), ss=w23+7; ss!=w23+8; ss+=1) *rr++ = *ss;
  /* #577: @37 = cos(@33) */
  w37 = cos( w33 );
  /* #578: @8 = (@8*@37) */
  w8 *= w37;
  /* #579: @31 = (@31+@8) */
  w31 += w8;
  /* #580: @8 = 0.2 */
  w8 = 2.0000000000000001e-01;
  /* #581: @8 = (@8*@17) */
  w8 *= w17;
  /* #582: @8 = (@8*@37) */
  w8 *= w37;
  /* #583: @32 = @23[8] */
  for (rr=(&w32), ss=w23+8; ss!=w23+9; ss+=1) *rr++ = *ss;
  /* #584: @30 = cos(@32) */
  w30 = cos( w32 );
  /* #585: @8 = (@8*@30) */
  w8 *= w30;
  /* #586: @31 = (@31+@8) */
  w31 += w8;
  /* #587: @8 = 0.2 */
  w8 = 2.0000000000000001e-01;
  /* #588: @8 = (@8*@17) */
  w8 *= w17;
  /* #589: @35 = sin(@33) */
  w35 = sin( w33 );
  /* #590: @8 = (@8*@35) */
  w8 *= w35;
  /* #591: @36 = sin(@32) */
  w36 = sin( w32 );
  /* #592: @8 = (@8*@36) */
  w8 *= w36;
  /* #593: @31 = (@31-@8) */
  w31 -= w8;
  /* #594: @8 = 0.0838 */
  w8 = 8.3799999999999999e-02;
  /* #595: @8 = (@8*@17) */
  w8 *= w17;
  /* #596: @9 = 0.2 */
  w9 = 2.0000000000000001e-01;
  /* #597: @9 = (@9*@37) */
  w9 *= w37;
  /* #598: @9 = (@9*@34) */
  w9 *= w34;
  /* #599: @8 = (@8+@9) */
  w8 += w9;
  /* #600: @9 = 0.2 */
  w9 = 2.0000000000000001e-01;
  /* #601: @9 = (@9*@37) */
  w9 *= w37;
  /* #602: @9 = (@9*@30) */
  w9 *= w30;
  /* #603: @9 = (@9*@34) */
  w9 *= w34;
  /* #604: @8 = (@8+@9) */
  w8 += w9;
  /* #605: @9 = 0.2 */
  w9 = 2.0000000000000001e-01;
  /* #606: @9 = (@9*@34) */
  w9 *= w34;
  /* #607: @9 = (@9*@35) */
  w9 *= w35;
  /* #608: @9 = (@9*@36) */
  w9 *= w36;
  /* #609: @8 = (@8-@9) */
  w8 -= w9;
  /* #610: @9 = 0.2 */
  w9 = 2.0000000000000001e-01;
  /* #611: @33 = (@33+@32) */
  w33 += w32;
  /* #612: @32 = cos(@33) */
  w32 = cos( w33 );
  /* #613: @9 = (@9*@32) */
  w9 *= w32;
  /* #614: @9 = (-@9) */
  w9 = (- w9 );
  /* #615: @32 = 0.2 */
  w32 = 2.0000000000000001e-01;
  /* #616: @32 = (@32*@37) */
  w32 *= w37;
  /* #617: @32 = (@9-@32) */
  w32  = (w9-w32);
  /* #618: @37 = 0.2 */
  w37 = 2.0000000000000001e-01;
  /* #619: @37 = (@37*@35) */
  w37 *= w35;
  /* #620: @35 = 0.2 */
  w35 = 2.0000000000000001e-01;
  /* #621: @33 = sin(@33) */
  w33 = sin( w33 );
  /* #622: @35 = (@35*@33) */
  w35 *= w33;
  /* #623: @37 = (@37+@35) */
  w37 += w35;
  /* #624: @33 = (@34*@37) */
  w33  = (w34*w37);
  /* #625: @33 = (-@33) */
  w33 = (- w33 );
  /* #626: @37 = (@17*@37) */
  w37  = (w17*w37);
  /* #627: @34 = (@34*@35) */
  w34 *= w35;
  /* #628: @34 = (-@34) */
  w34 = (- w34 );
  /* #629: @17 = (@17*@35) */
  w17 *= w35;
  /* #630: @4 = horzcat(@15, @31, @8, @32, @33, @37, @9, @34, @17) */
  rr=w4;
  *rr++ = w15;
  *rr++ = w31;
  *rr++ = w8;
  *rr++ = w32;
  *rr++ = w33;
  *rr++ = w37;
  *rr++ = w9;
  *rr++ = w34;
  *rr++ = w17;
  /* #631: @4 = reshape(@4) */
  /* #632: @4 = (-@4) */
  for (i=0, rr=w4, cs=w4; i<9; ++i) *rr++ = (- *cs++ );
  /* #633: @45 = @38[6:9] */
  for (rr=w45, ss=w38+6; ss!=w38+9; ss+=1) *rr++ = *ss;
  /* #634: @43 = mac(@4,@45,@43) */
  for (i=0, rr=w43; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #635: @45 = zeros(3x1) */
  casadi_clear(w45, 3);
  /* #636: @15 = 0 */
  w15 = 0.;
  /* #637: @31 = @40[2] */
  for (rr=(&w31), ss=w40+2; ss!=w40+3; ss+=1) *rr++ = *ss;
  /* #638: @8 = (-@31) */
  w8 = (- w31 );
  /* #639: @32 = @40[1] */
  for (rr=(&w32), ss=w40+1; ss!=w40+2; ss+=1) *rr++ = *ss;
  /* #640: @46 = horzcat(@15, @8, @32) */
  rr=w46;
  *rr++ = w15;
  *rr++ = w8;
  *rr++ = w32;
  /* #641: @46 = @46' */
  /* #642: @15 = 0 */
  w15 = 0.;
  /* #643: @8 = @40[0] */
  for (rr=(&w8), ss=w40+0; ss!=w40+1; ss+=1) *rr++ = *ss;
  /* #644: @33 = (-@8) */
  w33 = (- w8 );
  /* #645: @47 = horzcat(@31, @15, @33) */
  rr=w47;
  *rr++ = w31;
  *rr++ = w15;
  *rr++ = w33;
  /* #646: @47 = @47' */
  /* #647: @32 = (-@32) */
  w32 = (- w32 );
  /* #648: @31 = 0 */
  w31 = 0.;
  /* #649: @48 = horzcat(@32, @8, @31) */
  rr=w48;
  *rr++ = w32;
  *rr++ = w8;
  *rr++ = w31;
  /* #650: @48 = @48' */
  /* #651: @4 = horzcat(@46, @47, @48) */
  rr=w4;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w47; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w48; i<3; ++i) *rr++ = *cs++;
  /* #652: @44 = @4' */
  for (i=0, rr=w44, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #653: @32 = -0.1805 */
  w32 = -1.8049999999999999e-01;
  /* #654: @8 = 0.2 */
  w8 = 2.0000000000000001e-01;
  /* #655: @31 = @23[7] */
  for (rr=(&w31), ss=w23+7; ss!=w23+8; ss+=1) *rr++ = *ss;
  /* #656: @15 = sin(@31) */
  w15 = sin( w31 );
  /* #657: @8 = (@8*@15) */
  w8 *= w15;
  /* #658: @32 = (@32-@8) */
  w32 -= w8;
  /* #659: @8 = 0.2 */
  w8 = 2.0000000000000001e-01;
  /* #660: @33 = @23[8] */
  for (rr=(&w33), ss=w23+8; ss!=w23+9; ss+=1) *rr++ = *ss;
  /* #661: @37 = (@31+@33) */
  w37  = (w31+w33);
  /* #662: @37 = sin(@37) */
  w37 = sin( w37 );
  /* #663: @8 = (@8*@37) */
  w8 *= w37;
  /* #664: @32 = (@32-@8) */
  w32 -= w8;
  /* #665: @8 = 0.047 */
  w8 = 4.7000000000000000e-02;
  /* #666: @37 = 0.0838 */
  w37 = 8.3799999999999999e-02;
  /* #667: @9 = @23[6] */
  for (rr=(&w9), ss=w23+6; ss!=w23+7; ss+=1) *rr++ = *ss;
  /* #668: @34 = cos(@9) */
  w34 = cos( w9 );
  /* #669: @37 = (@37*@34) */
  w37 *= w34;
  /* #670: @8 = (@8+@37) */
  w8 += w37;
  /* #671: @37 = 0.2 */
  w37 = 2.0000000000000001e-01;
  /* #672: @31 = cos(@31) */
  w31 = cos( w31 );
  /* #673: @37 = (@37*@31) */
  w37 *= w31;
  /* #674: @9 = sin(@9) */
  w9 = sin( w9 );
  /* #675: @37 = (@37*@9) */
  w37 *= w9;
  /* #676: @8 = (@8+@37) */
  w8 += w37;
  /* #677: @37 = 0.2 */
  w37 = 2.0000000000000001e-01;
  /* #678: @37 = (@37*@31) */
  w37 *= w31;
  /* #679: @17 = cos(@33) */
  w17 = cos( w33 );
  /* #680: @37 = (@37*@17) */
  w37 *= w17;
  /* #681: @37 = (@37*@9) */
  w37 *= w9;
  /* #682: @8 = (@8+@37) */
  w8 += w37;
  /* #683: @37 = 0.2 */
  w37 = 2.0000000000000001e-01;
  /* #684: @37 = (@37*@9) */
  w37 *= w9;
  /* #685: @37 = (@37*@15) */
  w37 *= w15;
  /* #686: @33 = sin(@33) */
  w33 = sin( w33 );
  /* #687: @37 = (@37*@33) */
  w37 *= w33;
  /* #688: @8 = (@8-@37) */
  w8 -= w37;
  /* #689: @37 = 0.0838 */
  w37 = 8.3799999999999999e-02;
  /* #690: @37 = (@37*@9) */
  w37 *= w9;
  /* #691: @9 = 0.2 */
  w9 = 2.0000000000000001e-01;
  /* #692: @9 = (@9*@34) */
  w9 *= w34;
  /* #693: @9 = (@9*@31) */
  w9 *= w31;
  /* #694: @37 = (@37-@9) */
  w37 -= w9;
  /* #695: @9 = 0.2 */
  w9 = 2.0000000000000001e-01;
  /* #696: @9 = (@9*@34) */
  w9 *= w34;
  /* #697: @9 = (@9*@31) */
  w9 *= w31;
  /* #698: @9 = (@9*@17) */
  w9 *= w17;
  /* #699: @37 = (@37-@9) */
  w37 -= w9;
  /* #700: @9 = 0.2 */
  w9 = 2.0000000000000001e-01;
  /* #701: @9 = (@9*@34) */
  w9 *= w34;
  /* #702: @9 = (@9*@15) */
  w9 *= w15;
  /* #703: @9 = (@9*@33) */
  w9 *= w33;
  /* #704: @37 = (@37+@9) */
  w37 += w9;
  /* #705: @46 = vertcat(@32, @8, @37) */
  rr=w46;
  *rr++ = w32;
  *rr++ = w8;
  *rr++ = w37;
  /* #706: @45 = mac(@44,@46,@45) */
  for (i=0, rr=w45; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w44+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #707: @43 = (@43-@45) */
  for (i=0, rr=w43, cs=w45; i<3; ++i) (*rr++) -= (*cs++);
  /* #708: @2 = mac(@3,@43,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w43+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #709: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #710: @2 = @2' */
  /* #711: (@1[17:20] += @2) */
  for (rr=w1+17, ss=w2; rr!=w1+20; rr+=1) *rr += *ss++;
  /* #712: @32 = 0 */
  w32 = 0.;
  /* #713: (@1[20] = @32) */
  for (rr=w1+20, ss=(&w32); rr!=w1+21; rr+=1) *rr = *ss++;
  /* #714: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #715: (@1[21:24] = @2) */
  for (rr=w1+21, ss=w2; rr!=w1+24; rr+=1) *rr = *ss++;
  /* #716: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #717: @44 = @3' */
  for (i=0, rr=w44, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #718: @45 = @5[18:21] */
  for (rr=w45, ss=w5+18; ss!=w5+21; ss+=1) *rr++ = *ss;
  /* #719: @45 = (@45-@11) */
  for (i=0, rr=w45, cs=w11; i<3; ++i) (*rr++) -= (*cs++);
  /* #720: @2 = mac(@44,@45,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w44+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #721: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #722: @2 = @2' */
  /* #723: (@1[21:24] += @2) */
  for (rr=w1+21, ss=w2; rr!=w1+24; rr+=1) *rr += *ss++;
  /* #724: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #725: (@1[24:27] = @2) */
  for (rr=w1+24, ss=w2; rr!=w1+27; rr+=1) *rr = *ss++;
  /* #726: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #727: @11 = zeros(3x1) */
  casadi_clear(w11, 3);
  /* #728: @32 = 0 */
  w32 = 0.;
  /* #729: @8 = 0.0838 */
  w8 = 8.3799999999999999e-02;
  /* #730: @37 = @23[9] */
  for (rr=(&w37), ss=w23+9; ss!=w23+10; ss+=1) *rr++ = *ss;
  /* #731: @9 = sin(@37) */
  w9 = sin( w37 );
  /* #732: @8 = (@8*@9) */
  w8 *= w9;
  /* #733: @33 = 0.2 */
  w33 = 2.0000000000000001e-01;
  /* #734: @37 = cos(@37) */
  w37 = cos( w37 );
  /* #735: @33 = (@33*@37) */
  w33 *= w37;
  /* #736: @15 = @23[10] */
  for (rr=(&w15), ss=w23+10; ss!=w23+11; ss+=1) *rr++ = *ss;
  /* #737: @34 = cos(@15) */
  w34 = cos( w15 );
  /* #738: @33 = (@33*@34) */
  w33 *= w34;
  /* #739: @8 = (@8+@33) */
  w8 += w33;
  /* #740: @33 = 0.2 */
  w33 = 2.0000000000000001e-01;
  /* #741: @33 = (@33*@37) */
  w33 *= w37;
  /* #742: @33 = (@33*@34) */
  w33 *= w34;
  /* #743: @17 = @23[11] */
  for (rr=(&w17), ss=w23+11; ss!=w23+12; ss+=1) *rr++ = *ss;
  /* #744: @31 = cos(@17) */
  w31 = cos( w17 );
  /* #745: @33 = (@33*@31) */
  w33 *= w31;
  /* #746: @8 = (@8+@33) */
  w8 += w33;
  /* #747: @33 = 0.2 */
  w33 = 2.0000000000000001e-01;
  /* #748: @33 = (@33*@37) */
  w33 *= w37;
  /* #749: @35 = sin(@15) */
  w35 = sin( w15 );
  /* #750: @33 = (@33*@35) */
  w33 *= w35;
  /* #751: @36 = sin(@17) */
  w36 = sin( w17 );
  /* #752: @33 = (@33*@36) */
  w33 *= w36;
  /* #753: @8 = (@8-@33) */
  w8 -= w33;
  /* #754: @33 = -0.0838 */
  w33 = -8.3799999999999999e-02;
  /* #755: @33 = (@33*@37) */
  w33 *= w37;
  /* #756: @30 = 0.2 */
  w30 = 2.0000000000000001e-01;
  /* #757: @30 = (@30*@34) */
  w30 *= w34;
  /* #758: @30 = (@30*@9) */
  w30 *= w9;
  /* #759: @33 = (@33+@30) */
  w33 += w30;
  /* #760: @30 = 0.2 */
  w30 = 2.0000000000000001e-01;
  /* #761: @30 = (@30*@34) */
  w30 *= w34;
  /* #762: @30 = (@30*@31) */
  w30 *= w31;
  /* #763: @30 = (@30*@9) */
  w30 *= w9;
  /* #764: @33 = (@33+@30) */
  w33 += w30;
  /* #765: @30 = 0.2 */
  w30 = 2.0000000000000001e-01;
  /* #766: @30 = (@30*@9) */
  w30 *= w9;
  /* #767: @30 = (@30*@35) */
  w30 *= w35;
  /* #768: @30 = (@30*@36) */
  w30 *= w36;
  /* #769: @33 = (@33-@30) */
  w33 -= w30;
  /* #770: @30 = 0.2 */
  w30 = 2.0000000000000001e-01;
  /* #771: @15 = (@15+@17) */
  w15 += w17;
  /* #772: @17 = cos(@15) */
  w17 = cos( w15 );
  /* #773: @30 = (@30*@17) */
  w30 *= w17;
  /* #774: @30 = (-@30) */
  w30 = (- w30 );
  /* #775: @17 = 0.2 */
  w17 = 2.0000000000000001e-01;
  /* #776: @17 = (@17*@34) */
  w17 *= w34;
  /* #777: @17 = (@30-@17) */
  w17  = (w30-w17);
  /* #778: @34 = 0.2 */
  w34 = 2.0000000000000001e-01;
  /* #779: @34 = (@34*@35) */
  w34 *= w35;
  /* #780: @35 = 0.2 */
  w35 = 2.0000000000000001e-01;
  /* #781: @15 = sin(@15) */
  w15 = sin( w15 );
  /* #782: @35 = (@35*@15) */
  w35 *= w15;
  /* #783: @34 = (@34+@35) */
  w34 += w35;
  /* #784: @15 = (@9*@34) */
  w15  = (w9*w34);
  /* #785: @15 = (-@15) */
  w15 = (- w15 );
  /* #786: @34 = (@37*@34) */
  w34  = (w37*w34);
  /* #787: @9 = (@9*@35) */
  w9 *= w35;
  /* #788: @9 = (-@9) */
  w9 = (- w9 );
  /* #789: @37 = (@37*@35) */
  w37 *= w35;
  /* #790: @44 = horzcat(@32, @8, @33, @17, @15, @34, @30, @9, @37) */
  rr=w44;
  *rr++ = w32;
  *rr++ = w8;
  *rr++ = w33;
  *rr++ = w17;
  *rr++ = w15;
  *rr++ = w34;
  *rr++ = w30;
  *rr++ = w9;
  *rr++ = w37;
  /* #791: @44 = reshape(@44) */
  /* #792: @44 = (-@44) */
  for (i=0, rr=w44, cs=w44; i<9; ++i) *rr++ = (- *cs++ );
  /* #793: @46 = @38[9:12] */
  for (rr=w46, ss=w38+9; ss!=w38+12; ss+=1) *rr++ = *ss;
  /* #794: @11 = mac(@44,@46,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w44+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #795: @46 = zeros(3x1) */
  casadi_clear(w46, 3);
  /* #796: @32 = 0 */
  w32 = 0.;
  /* #797: @8 = @40[2] */
  for (rr=(&w8), ss=w40+2; ss!=w40+3; ss+=1) *rr++ = *ss;
  /* #798: @33 = (-@8) */
  w33 = (- w8 );
  /* #799: @17 = @40[1] */
  for (rr=(&w17), ss=w40+1; ss!=w40+2; ss+=1) *rr++ = *ss;
  /* #800: @47 = horzcat(@32, @33, @17) */
  rr=w47;
  *rr++ = w32;
  *rr++ = w33;
  *rr++ = w17;
  /* #801: @47 = @47' */
  /* #802: @32 = 0 */
  w32 = 0.;
  /* #803: @33 = @40[0] */
  for (rr=(&w33), ss=w40+0; ss!=w40+1; ss+=1) *rr++ = *ss;
  /* #804: @15 = (-@33) */
  w15 = (- w33 );
  /* #805: @40 = horzcat(@8, @32, @15) */
  rr=w40;
  *rr++ = w8;
  *rr++ = w32;
  *rr++ = w15;
  /* #806: @40 = @40' */
  /* #807: @17 = (-@17) */
  w17 = (- w17 );
  /* #808: @8 = 0 */
  w8 = 0.;
  /* #809: @48 = horzcat(@17, @33, @8) */
  rr=w48;
  *rr++ = w17;
  *rr++ = w33;
  *rr++ = w8;
  /* #810: @48 = @48' */
  /* #811: @44 = horzcat(@47, @40, @48) */
  rr=w44;
  for (i=0, cs=w47; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w48; i<3; ++i) *rr++ = *cs++;
  /* #812: @4 = @44' */
  for (i=0, rr=w4, cs=w44; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #813: @17 = -0.1805 */
  w17 = -1.8049999999999999e-01;
  /* #814: @33 = 0.2 */
  w33 = 2.0000000000000001e-01;
  /* #815: @8 = @23[10] */
  for (rr=(&w8), ss=w23+10; ss!=w23+11; ss+=1) *rr++ = *ss;
  /* #816: @32 = sin(@8) */
  w32 = sin( w8 );
  /* #817: @33 = (@33*@32) */
  w33 *= w32;
  /* #818: @17 = (@17-@33) */
  w17 -= w33;
  /* #819: @33 = 0.2 */
  w33 = 2.0000000000000001e-01;
  /* #820: @15 = @23[11] */
  for (rr=(&w15), ss=w23+11; ss!=w23+12; ss+=1) *rr++ = *ss;
  /* #821: @34 = (@8+@15) */
  w34  = (w8+w15);
  /* #822: @34 = sin(@34) */
  w34 = sin( w34 );
  /* #823: @33 = (@33*@34) */
  w33 *= w34;
  /* #824: @17 = (@17-@33) */
  w17 -= w33;
  /* #825: @33 = -0.047 */
  w33 = -4.7000000000000000e-02;
  /* #826: @34 = -0.0838 */
  w34 = -8.3799999999999999e-02;
  /* #827: @30 = @23[9] */
  for (rr=(&w30), ss=w23+9; ss!=w23+10; ss+=1) *rr++ = *ss;
  /* #828: @9 = cos(@30) */
  w9 = cos( w30 );
  /* #829: @34 = (@34*@9) */
  w34 *= w9;
  /* #830: @33 = (@33+@34) */
  w33 += w34;
  /* #831: @34 = 0.2 */
  w34 = 2.0000000000000001e-01;
  /* #832: @8 = cos(@8) */
  w8 = cos( w8 );
  /* #833: @34 = (@34*@8) */
  w34 *= w8;
  /* #834: @30 = sin(@30) */
  w30 = sin( w30 );
  /* #835: @34 = (@34*@30) */
  w34 *= w30;
  /* #836: @33 = (@33+@34) */
  w33 += w34;
  /* #837: @34 = 0.2 */
  w34 = 2.0000000000000001e-01;
  /* #838: @34 = (@34*@8) */
  w34 *= w8;
  /* #839: @37 = cos(@15) */
  w37 = cos( w15 );
  /* #840: @34 = (@34*@37) */
  w34 *= w37;
  /* #841: @34 = (@34*@30) */
  w34 *= w30;
  /* #842: @33 = (@33+@34) */
  w33 += w34;
  /* #843: @34 = 0.2 */
  w34 = 2.0000000000000001e-01;
  /* #844: @34 = (@34*@30) */
  w34 *= w30;
  /* #845: @34 = (@34*@32) */
  w34 *= w32;
  /* #846: @15 = sin(@15) */
  w15 = sin( w15 );
  /* #847: @34 = (@34*@15) */
  w34 *= w15;
  /* #848: @33 = (@33-@34) */
  w33 -= w34;
  /* #849: @34 = -0.0838 */
  w34 = -8.3799999999999999e-02;
  /* #850: @34 = (@34*@30) */
  w34 *= w30;
  /* #851: @30 = 0.2 */
  w30 = 2.0000000000000001e-01;
  /* #852: @30 = (@30*@9) */
  w30 *= w9;
  /* #853: @30 = (@30*@8) */
  w30 *= w8;
  /* #854: @34 = (@34-@30) */
  w34 -= w30;
  /* #855: @30 = 0.2 */
  w30 = 2.0000000000000001e-01;
  /* #856: @30 = (@30*@9) */
  w30 *= w9;
  /* #857: @30 = (@30*@8) */
  w30 *= w8;
  /* #858: @30 = (@30*@37) */
  w30 *= w37;
  /* #859: @34 = (@34-@30) */
  w34 -= w30;
  /* #860: @30 = 0.2 */
  w30 = 2.0000000000000001e-01;
  /* #861: @30 = (@30*@9) */
  w30 *= w9;
  /* #862: @30 = (@30*@32) */
  w30 *= w32;
  /* #863: @30 = (@30*@15) */
  w30 *= w15;
  /* #864: @34 = (@34+@30) */
  w34 += w30;
  /* #865: @47 = vertcat(@17, @33, @34) */
  rr=w47;
  *rr++ = w17;
  *rr++ = w33;
  *rr++ = w34;
  /* #866: @46 = mac(@4,@47,@46) */
  for (i=0, rr=w46; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w47+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #867: @11 = (@11-@46) */
  for (i=0, rr=w11, cs=w46; i<3; ++i) (*rr++) -= (*cs++);
  /* #868: @2 = mac(@3,@11,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w11+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #869: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #870: @2 = @2' */
  /* #871: (@1[24:27] += @2) */
  for (rr=w1+24, ss=w2; rr!=w1+27; rr+=1) *rr += *ss++;
  /* #872: @17 = 0 */
  w17 = 0.;
  /* #873: (@1[27] = @17) */
  for (rr=w1+27, ss=(&w17); rr!=w1+28; rr+=1) *rr = *ss++;
  /* #874: @49 = @1[:28:7;1:6] */
  for (rr=w49, ss=w1+0; ss!=w1+28; ss+=7) for (tt=ss+1; tt!=ss+6; tt+=1) *rr++ = *tt;
  /* #875: (@0[11, 20, 27, 31, 35, 49, 58, 65, 69, 73, 87, 96, 103, 107, 111, 125, 134, 141, 145, 149] = @49) */
  for (cii=casadi_s9, rr=w0, ss=w49; cii!=casadi_s9+20; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #876: @1 = zeros(28x1) */
  casadi_clear(w1, 28);
  /* #877: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #878: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #879: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #880: @17 = sin(@7) */
  w17 = sin( w7 );
  /* #881: @17 = (-@17) */
  w17 = (- w17 );
  /* #882: @24 = 00 */
  /* #883: @33 = cos(@7) */
  w33 = cos( w7 );
  /* #884: @26 = horzcat(@17, @24, @33) */
  rr=w26;
  *rr++ = w17;
  *rr++ = w33;
  /* #885: @26 = @26' */
  /* #886: @24 = zeros(3x1,0nz) */
  /* #887: @17 = cos(@7) */
  w17 = cos( w7 );
  /* #888: @17 = (-@17) */
  w17 = (- w17 );
  /* #889: @25 = 00 */
  /* #890: @7 = sin(@7) */
  w7 = sin( w7 );
  /* #891: @7 = (-@7) */
  w7 = (- w7 );
  /* #892: @27 = horzcat(@17, @25, @7) */
  rr=w27;
  *rr++ = w17;
  *rr++ = w7;
  /* #893: @27 = @27' */
  /* #894: @29 = horzcat(@26, @24, @27) */
  rr=w29;
  for (i=0, cs=w26; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  /* #895: @28 = @29' */
  casadi_trans(w29,casadi_s10, w28, casadi_s10, iw);
  /* #896: @4 = mac(@14,@28,@4) */
  casadi_mtimes(w14, casadi_s2, w28, casadi_s10, w4, casadi_s2, w, 0);
  /* #897: @3 = mac(@4,@18,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #898: @4 = @3' */
  for (i=0, rr=w4, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #899: @2 = mac(@4,@10,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w10+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #900: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #901: @2 = @2' */
  /* #902: (@1[:3] += @2) */
  for (rr=w1+0, ss=w2; rr!=w1+3; rr+=1) *rr += *ss++;
  /* #903: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #904: (@1[3:6] = @2) */
  for (rr=w1+3, ss=w2; rr!=w1+6; rr+=1) *rr = *ss++;
  /* #905: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #906: @2 = mac(@3,@12,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #907: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #908: @2 = @2' */
  /* #909: (@1[3:6] += @2) */
  for (rr=w1+3, ss=w2; rr!=w1+6; rr+=1) *rr += *ss++;
  /* #910: @17 = 0 */
  w17 = 0.;
  /* #911: (@1[6] = @17) */
  for (rr=w1+6, ss=(&w17); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #912: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #913: (@1[7:10] = @2) */
  for (rr=w1+7, ss=w2; rr!=w1+10; rr+=1) *rr = *ss++;
  /* #914: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #915: @4 = @3' */
  for (i=0, rr=w4, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #916: @2 = mac(@4,@39,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w39+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #917: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #918: @2 = @2' */
  /* #919: (@1[7:10] += @2) */
  for (rr=w1+7, ss=w2; rr!=w1+10; rr+=1) *rr += *ss++;
  /* #920: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #921: (@1[10:13] = @2) */
  for (rr=w1+10, ss=w2; rr!=w1+13; rr+=1) *rr = *ss++;
  /* #922: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #923: @2 = mac(@3,@41,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #924: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #925: @2 = @2' */
  /* #926: (@1[10:13] += @2) */
  for (rr=w1+10, ss=w2; rr!=w1+13; rr+=1) *rr += *ss++;
  /* #927: @17 = 0 */
  w17 = 0.;
  /* #928: (@1[13] = @17) */
  for (rr=w1+13, ss=(&w17); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #929: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #930: (@1[14:17] = @2) */
  for (rr=w1+14, ss=w2; rr!=w1+17; rr+=1) *rr = *ss++;
  /* #931: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #932: @4 = @3' */
  for (i=0, rr=w4, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #933: @2 = mac(@4,@42,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w42+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #934: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #935: @2 = @2' */
  /* #936: (@1[14:17] += @2) */
  for (rr=w1+14, ss=w2; rr!=w1+17; rr+=1) *rr += *ss++;
  /* #937: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #938: (@1[17:20] = @2) */
  for (rr=w1+17, ss=w2; rr!=w1+20; rr+=1) *rr = *ss++;
  /* #939: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #940: @2 = mac(@3,@43,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w43+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #941: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #942: @2 = @2' */
  /* #943: (@1[17:20] += @2) */
  for (rr=w1+17, ss=w2; rr!=w1+20; rr+=1) *rr += *ss++;
  /* #944: @17 = 0 */
  w17 = 0.;
  /* #945: (@1[20] = @17) */
  for (rr=w1+20, ss=(&w17); rr!=w1+21; rr+=1) *rr = *ss++;
  /* #946: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #947: (@1[21:24] = @2) */
  for (rr=w1+21, ss=w2; rr!=w1+24; rr+=1) *rr = *ss++;
  /* #948: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #949: @4 = @3' */
  for (i=0, rr=w4, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #950: @2 = mac(@4,@45,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #951: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #952: @2 = @2' */
  /* #953: (@1[21:24] += @2) */
  for (rr=w1+21, ss=w2; rr!=w1+24; rr+=1) *rr += *ss++;
  /* #954: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #955: (@1[24:27] = @2) */
  for (rr=w1+24, ss=w2; rr!=w1+27; rr+=1) *rr = *ss++;
  /* #956: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #957: @2 = mac(@3,@11,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w11+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #958: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #959: @2 = @2' */
  /* #960: (@1[24:27] += @2) */
  for (rr=w1+24, ss=w2; rr!=w1+27; rr+=1) *rr += *ss++;
  /* #961: @17 = 0 */
  w17 = 0.;
  /* #962: (@1[27] = @17) */
  for (rr=w1+27, ss=(&w17); rr!=w1+28; rr+=1) *rr = *ss++;
  /* #963: @22 = @1[:28:7;:6] */
  for (rr=w22, ss=w1+0; ss!=w1+28; ss+=7) for (tt=ss+0; tt!=ss+6; tt+=1) *rr++ = *tt;
  /* #964: (@0[3, 12, 21, 28, 32, 36, 41, 50, 59, 66, 70, 74, 79, 88, 97, 104, 108, 112, 117, 126, 135, 142, 146, 150] = @22) */
  for (cii=casadi_s11, rr=w0, ss=w22; cii!=casadi_s11+24; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #965: @1 = zeros(28x1) */
  casadi_clear(w1, 28);
  /* #966: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #967: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #968: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #969: @17 = sin(@6) */
  w17 = sin( w6 );
  /* #970: @17 = (-@17) */
  w17 = (- w17 );
  /* #971: @7 = cos(@6) */
  w7 = cos( w6 );
  /* #972: @7 = (-@7) */
  w7 = (- w7 );
  /* #973: @24 = 00 */
  /* #974: @26 = horzcat(@17, @7, @24) */
  rr=w26;
  *rr++ = w17;
  *rr++ = w7;
  /* #975: @26 = @26' */
  /* #976: @17 = cos(@6) */
  w17 = cos( w6 );
  /* #977: @6 = sin(@6) */
  w6 = sin( w6 );
  /* #978: @6 = (-@6) */
  w6 = (- w6 );
  /* #979: @24 = 00 */
  /* #980: @27 = horzcat(@17, @6, @24) */
  rr=w27;
  *rr++ = w17;
  *rr++ = w6;
  /* #981: @27 = @27' */
  /* #982: @24 = zeros(3x1,0nz) */
  /* #983: @28 = horzcat(@26, @27, @24) */
  rr=w28;
  for (i=0, cs=w26; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  /* #984: @29 = @28' */
  casadi_trans(w28,casadi_s12, w29, casadi_s12, iw);
  /* #985: @4 = mac(@29,@16,@4) */
  casadi_mtimes(w29, casadi_s12, w16, casadi_s2, w4, casadi_s2, w, 0);
  /* #986: @3 = mac(@4,@18,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #987: @4 = @3' */
  for (i=0, rr=w4, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #988: @2 = mac(@4,@10,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w10+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #989: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #990: @2 = @2' */
  /* #991: (@1[:3] += @2) */
  for (rr=w1+0, ss=w2; rr!=w1+3; rr+=1) *rr += *ss++;
  /* #992: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #993: (@1[3:6] = @2) */
  for (rr=w1+3, ss=w2; rr!=w1+6; rr+=1) *rr = *ss++;
  /* #994: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #995: @2 = mac(@3,@12,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #996: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #997: @2 = @2' */
  /* #998: (@1[3:6] += @2) */
  for (rr=w1+3, ss=w2; rr!=w1+6; rr+=1) *rr += *ss++;
  /* #999: @17 = 0 */
  w17 = 0.;
  /* #1000: (@1[6] = @17) */
  for (rr=w1+6, ss=(&w17); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #1001: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1002: (@1[7:10] = @2) */
  for (rr=w1+7, ss=w2; rr!=w1+10; rr+=1) *rr = *ss++;
  /* #1003: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #1004: @4 = @3' */
  for (i=0, rr=w4, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #1005: @2 = mac(@4,@39,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w39+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1006: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #1007: @2 = @2' */
  /* #1008: (@1[7:10] += @2) */
  for (rr=w1+7, ss=w2; rr!=w1+10; rr+=1) *rr += *ss++;
  /* #1009: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1010: (@1[10:13] = @2) */
  for (rr=w1+10, ss=w2; rr!=w1+13; rr+=1) *rr = *ss++;
  /* #1011: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #1012: @2 = mac(@3,@41,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1013: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #1014: @2 = @2' */
  /* #1015: (@1[10:13] += @2) */
  for (rr=w1+10, ss=w2; rr!=w1+13; rr+=1) *rr += *ss++;
  /* #1016: @17 = 0 */
  w17 = 0.;
  /* #1017: (@1[13] = @17) */
  for (rr=w1+13, ss=(&w17); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #1018: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1019: (@1[14:17] = @2) */
  for (rr=w1+14, ss=w2; rr!=w1+17; rr+=1) *rr = *ss++;
  /* #1020: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #1021: @4 = @3' */
  for (i=0, rr=w4, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #1022: @2 = mac(@4,@42,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w42+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1023: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #1024: @2 = @2' */
  /* #1025: (@1[14:17] += @2) */
  for (rr=w1+14, ss=w2; rr!=w1+17; rr+=1) *rr += *ss++;
  /* #1026: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1027: (@1[17:20] = @2) */
  for (rr=w1+17, ss=w2; rr!=w1+20; rr+=1) *rr = *ss++;
  /* #1028: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #1029: @2 = mac(@3,@43,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w43+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1030: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #1031: @2 = @2' */
  /* #1032: (@1[17:20] += @2) */
  for (rr=w1+17, ss=w2; rr!=w1+20; rr+=1) *rr += *ss++;
  /* #1033: @17 = 0 */
  w17 = 0.;
  /* #1034: (@1[20] = @17) */
  for (rr=w1+20, ss=(&w17); rr!=w1+21; rr+=1) *rr = *ss++;
  /* #1035: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1036: (@1[21:24] = @2) */
  for (rr=w1+21, ss=w2; rr!=w1+24; rr+=1) *rr = *ss++;
  /* #1037: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #1038: @4 = @3' */
  for (i=0, rr=w4, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #1039: @2 = mac(@4,@45,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1040: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #1041: @2 = @2' */
  /* #1042: (@1[21:24] += @2) */
  for (rr=w1+21, ss=w2; rr!=w1+24; rr+=1) *rr += *ss++;
  /* #1043: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1044: (@1[24:27] = @2) */
  for (rr=w1+24, ss=w2; rr!=w1+27; rr+=1) *rr = *ss++;
  /* #1045: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #1046: @2 = mac(@3,@11,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w11+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1047: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #1048: @2 = @2' */
  /* #1049: (@1[24:27] += @2) */
  for (rr=w1+24, ss=w2; rr!=w1+27; rr+=1) *rr += *ss++;
  /* #1050: @17 = 0 */
  w17 = 0.;
  /* #1051: (@1[27] = @17) */
  for (rr=w1+27, ss=(&w17); rr!=w1+28; rr+=1) *rr = *ss++;
  /* #1052: @49 = @1[:28:7;:5] */
  for (rr=w49, ss=w1+0; ss!=w1+28; ss+=7) for (tt=ss+0; tt!=ss+5; tt+=1) *rr++ = *tt;
  /* #1053: (@0[4, 13, 22, 29, 33, 42, 51, 60, 67, 71, 80, 89, 98, 105, 109, 118, 127, 136, 143, 147] = @49) */
  for (cii=casadi_s13, rr=w0, ss=w49; cii!=casadi_s13+20; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #1054: @1 = zeros(28x1) */
  casadi_clear(w1, 28);
  /* #1055: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #1056: @17 = ones(3x1,1nz) */
  w17 = 1.;
  /* #1057: @2 = mac(@13,@17,@2) */
  casadi_mtimes(w13, casadi_s2, (&w17), casadi_s1, w2, casadi_s0, w, 0);
  /* #1058: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #1059: @2 = @2' */
  /* #1060: (@1[:3] += @2) */
  for (rr=w1+0, ss=w2; rr!=w1+3; rr+=1) *rr += *ss++;
  /* #1061: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1062: (@1[3:6] = @2) */
  for (rr=w1+3, ss=w2; rr!=w1+6; rr+=1) *rr = *ss++;
  /* #1063: @17 = 0 */
  w17 = 0.;
  /* #1064: (@1[6] = @17) */
  for (rr=w1+6, ss=(&w17); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #1065: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1066: (@1[7:10] = @2) */
  for (rr=w1+7, ss=w2; rr!=w1+10; rr+=1) *rr = *ss++;
  /* #1067: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #1068: @17 = ones(3x1,1nz) */
  w17 = 1.;
  /* #1069: @2 = mac(@19,@17,@2) */
  casadi_mtimes(w19, casadi_s2, (&w17), casadi_s1, w2, casadi_s0, w, 0);
  /* #1070: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #1071: @2 = @2' */
  /* #1072: (@1[7:10] += @2) */
  for (rr=w1+7, ss=w2; rr!=w1+10; rr+=1) *rr += *ss++;
  /* #1073: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1074: (@1[10:13] = @2) */
  for (rr=w1+10, ss=w2; rr!=w1+13; rr+=1) *rr = *ss++;
  /* #1075: @17 = 0 */
  w17 = 0.;
  /* #1076: (@1[13] = @17) */
  for (rr=w1+13, ss=(&w17); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #1077: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1078: (@1[14:17] = @2) */
  for (rr=w1+14, ss=w2; rr!=w1+17; rr+=1) *rr = *ss++;
  /* #1079: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #1080: @17 = ones(3x1,1nz) */
  w17 = 1.;
  /* #1081: @2 = mac(@20,@17,@2) */
  casadi_mtimes(w20, casadi_s2, (&w17), casadi_s1, w2, casadi_s0, w, 0);
  /* #1082: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #1083: @2 = @2' */
  /* #1084: (@1[14:17] += @2) */
  for (rr=w1+14, ss=w2; rr!=w1+17; rr+=1) *rr += *ss++;
  /* #1085: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1086: (@1[17:20] = @2) */
  for (rr=w1+17, ss=w2; rr!=w1+20; rr+=1) *rr = *ss++;
  /* #1087: @17 = 0 */
  w17 = 0.;
  /* #1088: (@1[20] = @17) */
  for (rr=w1+20, ss=(&w17); rr!=w1+21; rr+=1) *rr = *ss++;
  /* #1089: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1090: (@1[21:24] = @2) */
  for (rr=w1+21, ss=w2; rr!=w1+24; rr+=1) *rr = *ss++;
  /* #1091: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #1092: @17 = ones(3x1,1nz) */
  w17 = 1.;
  /* #1093: @2 = mac(@21,@17,@2) */
  casadi_mtimes(w21, casadi_s2, (&w17), casadi_s1, w2, casadi_s0, w, 0);
  /* #1094: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #1095: @2 = @2' */
  /* #1096: (@1[21:24] += @2) */
  for (rr=w1+21, ss=w2; rr!=w1+24; rr+=1) *rr += *ss++;
  /* #1097: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1098: (@1[24:27] = @2) */
  for (rr=w1+24, ss=w2; rr!=w1+27; rr+=1) *rr = *ss++;
  /* #1099: @17 = 0 */
  w17 = 0.;
  /* #1100: (@1[27] = @17) */
  for (rr=w1+27, ss=(&w17); rr!=w1+28; rr+=1) *rr = *ss++;
  /* #1101: @23 = @1[:28:7;:3] */
  for (rr=w23, ss=w1+0; ss!=w1+28; ss+=7) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #1102: (@0[:152:38;5:32:9] = @23) */
  for (rr=w0+0, ss=w23; rr!=w0+152; rr+=38) for (tt=rr+5; tt!=rr+32; tt+=9) *tt = *ss++;
  /* #1103: @1 = zeros(28x1) */
  casadi_clear(w1, 28);
  /* #1104: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #1105: @17 = ones(3x1,1nz) */
  w17 = 1.;
  /* #1106: @2 = mac(@13,@17,@2) */
  casadi_mtimes(w13, casadi_s2, (&w17), casadi_s4, w2, casadi_s0, w, 0);
  /* #1107: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #1108: @2 = @2' */
  /* #1109: (@1[:3] += @2) */
  for (rr=w1+0, ss=w2; rr!=w1+3; rr+=1) *rr += *ss++;
  /* #1110: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1111: (@1[3:6] = @2) */
  for (rr=w1+3, ss=w2; rr!=w1+6; rr+=1) *rr = *ss++;
  /* #1112: @17 = 0 */
  w17 = 0.;
  /* #1113: (@1[6] = @17) */
  for (rr=w1+6, ss=(&w17); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #1114: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1115: (@1[7:10] = @2) */
  for (rr=w1+7, ss=w2; rr!=w1+10; rr+=1) *rr = *ss++;
  /* #1116: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #1117: @17 = ones(3x1,1nz) */
  w17 = 1.;
  /* #1118: @2 = mac(@19,@17,@2) */
  casadi_mtimes(w19, casadi_s2, (&w17), casadi_s4, w2, casadi_s0, w, 0);
  /* #1119: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #1120: @2 = @2' */
  /* #1121: (@1[7:10] += @2) */
  for (rr=w1+7, ss=w2; rr!=w1+10; rr+=1) *rr += *ss++;
  /* #1122: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1123: (@1[10:13] = @2) */
  for (rr=w1+10, ss=w2; rr!=w1+13; rr+=1) *rr = *ss++;
  /* #1124: @17 = 0 */
  w17 = 0.;
  /* #1125: (@1[13] = @17) */
  for (rr=w1+13, ss=(&w17); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #1126: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1127: (@1[14:17] = @2) */
  for (rr=w1+14, ss=w2; rr!=w1+17; rr+=1) *rr = *ss++;
  /* #1128: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #1129: @17 = ones(3x1,1nz) */
  w17 = 1.;
  /* #1130: @2 = mac(@20,@17,@2) */
  casadi_mtimes(w20, casadi_s2, (&w17), casadi_s4, w2, casadi_s0, w, 0);
  /* #1131: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #1132: @2 = @2' */
  /* #1133: (@1[14:17] += @2) */
  for (rr=w1+14, ss=w2; rr!=w1+17; rr+=1) *rr += *ss++;
  /* #1134: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1135: (@1[17:20] = @2) */
  for (rr=w1+17, ss=w2; rr!=w1+20; rr+=1) *rr = *ss++;
  /* #1136: @17 = 0 */
  w17 = 0.;
  /* #1137: (@1[20] = @17) */
  for (rr=w1+20, ss=(&w17); rr!=w1+21; rr+=1) *rr = *ss++;
  /* #1138: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1139: (@1[21:24] = @2) */
  for (rr=w1+21, ss=w2; rr!=w1+24; rr+=1) *rr = *ss++;
  /* #1140: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #1141: @17 = ones(3x1,1nz) */
  w17 = 1.;
  /* #1142: @2 = mac(@21,@17,@2) */
  casadi_mtimes(w21, casadi_s2, (&w17), casadi_s4, w2, casadi_s0, w, 0);
  /* #1143: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #1144: @2 = @2' */
  /* #1145: (@1[21:24] += @2) */
  for (rr=w1+21, ss=w2; rr!=w1+24; rr+=1) *rr += *ss++;
  /* #1146: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1147: (@1[24:27] = @2) */
  for (rr=w1+24, ss=w2; rr!=w1+27; rr+=1) *rr = *ss++;
  /* #1148: @17 = 0 */
  w17 = 0.;
  /* #1149: (@1[27] = @17) */
  for (rr=w1+27, ss=(&w17); rr!=w1+28; rr+=1) *rr = *ss++;
  /* #1150: @23 = @1[:28:7;:3] */
  for (rr=w23, ss=w1+0; ss!=w1+28; ss+=7) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #1151: (@0[:152:38;6:33:9] = @23) */
  for (rr=w0+0, ss=w23; rr!=w0+152; rr+=38) for (tt=rr+6; tt!=rr+33; tt+=9) *tt = *ss++;
  /* #1152: @1 = zeros(28x1) */
  casadi_clear(w1, 28);
  /* #1153: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #1154: @17 = ones(3x1,1nz) */
  w17 = 1.;
  /* #1155: @2 = mac(@13,@17,@2) */
  casadi_mtimes(w13, casadi_s2, (&w17), casadi_s6, w2, casadi_s0, w, 0);
  /* #1156: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #1157: @2 = @2' */
  /* #1158: (@1[:3] += @2) */
  for (rr=w1+0, ss=w2; rr!=w1+3; rr+=1) *rr += *ss++;
  /* #1159: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1160: (@1[3:6] = @2) */
  for (rr=w1+3, ss=w2; rr!=w1+6; rr+=1) *rr = *ss++;
  /* #1161: @17 = 0 */
  w17 = 0.;
  /* #1162: (@1[6] = @17) */
  for (rr=w1+6, ss=(&w17); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #1163: @17 = 1 */
  w17 = 1.;
  /* #1164: (@1[6] += @17) */
  for (rr=w1+6, ss=(&w17); rr!=w1+7; rr+=1) *rr += *ss++;
  /* #1165: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1166: (@1[7:10] = @2) */
  for (rr=w1+7, ss=w2; rr!=w1+10; rr+=1) *rr = *ss++;
  /* #1167: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #1168: @17 = ones(3x1,1nz) */
  w17 = 1.;
  /* #1169: @2 = mac(@19,@17,@2) */
  casadi_mtimes(w19, casadi_s2, (&w17), casadi_s6, w2, casadi_s0, w, 0);
  /* #1170: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #1171: @2 = @2' */
  /* #1172: (@1[7:10] += @2) */
  for (rr=w1+7, ss=w2; rr!=w1+10; rr+=1) *rr += *ss++;
  /* #1173: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1174: (@1[10:13] = @2) */
  for (rr=w1+10, ss=w2; rr!=w1+13; rr+=1) *rr = *ss++;
  /* #1175: @17 = 0 */
  w17 = 0.;
  /* #1176: (@1[13] = @17) */
  for (rr=w1+13, ss=(&w17); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #1177: @17 = 1 */
  w17 = 1.;
  /* #1178: (@1[13] += @17) */
  for (rr=w1+13, ss=(&w17); rr!=w1+14; rr+=1) *rr += *ss++;
  /* #1179: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1180: (@1[14:17] = @2) */
  for (rr=w1+14, ss=w2; rr!=w1+17; rr+=1) *rr = *ss++;
  /* #1181: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #1182: @17 = ones(3x1,1nz) */
  w17 = 1.;
  /* #1183: @2 = mac(@20,@17,@2) */
  casadi_mtimes(w20, casadi_s2, (&w17), casadi_s6, w2, casadi_s0, w, 0);
  /* #1184: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #1185: @2 = @2' */
  /* #1186: (@1[14:17] += @2) */
  for (rr=w1+14, ss=w2; rr!=w1+17; rr+=1) *rr += *ss++;
  /* #1187: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1188: (@1[17:20] = @2) */
  for (rr=w1+17, ss=w2; rr!=w1+20; rr+=1) *rr = *ss++;
  /* #1189: @17 = 0 */
  w17 = 0.;
  /* #1190: (@1[20] = @17) */
  for (rr=w1+20, ss=(&w17); rr!=w1+21; rr+=1) *rr = *ss++;
  /* #1191: @17 = 1 */
  w17 = 1.;
  /* #1192: (@1[20] += @17) */
  for (rr=w1+20, ss=(&w17); rr!=w1+21; rr+=1) *rr += *ss++;
  /* #1193: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1194: (@1[21:24] = @2) */
  for (rr=w1+21, ss=w2; rr!=w1+24; rr+=1) *rr = *ss++;
  /* #1195: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #1196: @17 = ones(3x1,1nz) */
  w17 = 1.;
  /* #1197: @2 = mac(@21,@17,@2) */
  casadi_mtimes(w21, casadi_s2, (&w17), casadi_s6, w2, casadi_s0, w, 0);
  /* #1198: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #1199: @2 = @2' */
  /* #1200: (@1[21:24] += @2) */
  for (rr=w1+21, ss=w2; rr!=w1+24; rr+=1) *rr += *ss++;
  /* #1201: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #1202: (@1[24:27] = @2) */
  for (rr=w1+24, ss=w2; rr!=w1+27; rr+=1) *rr = *ss++;
  /* #1203: @17 = 0 */
  w17 = 0.;
  /* #1204: (@1[27] = @17) */
  for (rr=w1+27, ss=(&w17); rr!=w1+28; rr+=1) *rr = *ss++;
  /* #1205: @17 = 1 */
  w17 = 1.;
  /* #1206: (@1[27] += @17) */
  for (rr=w1+27, ss=(&w17); rr!=w1+28; rr+=1) *rr += *ss++;
  /* #1207: @50 = @1[0, 1, 2, 6, 7, 8, 9, 13, 14, 15, 16, 20, 21, 22, 23, 27] */
  for (cii=casadi_s14, rr=w50, ss=w1; cii!=casadi_s14+16; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #1208: (@0[7, 16, 25, 37, 45, 54, 63, 75, 83, 92, 101, 113, 121, 130, 139, 151] = @50) */
  for (cii=casadi_s15, rr=w0, ss=w50; cii!=casadi_s15+16; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #1209: @51 = @0' */
  casadi_trans(w0,casadi_s17, w51, casadi_s16, iw);
  /* #1210: output[0][0] = @51 */
  casadi_copy(w51, 152, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int meas_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int meas_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int meas_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void meas_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int meas_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void meas_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void meas_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void meas_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int meas_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int meas_jac_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real meas_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* meas_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* meas_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* meas_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s18;
    case 1: return casadi_s0;
    case 2: return casadi_s19;
    case 3: return casadi_s19;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* meas_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s16;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int meas_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 13;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 23;
  if (sz_w) *sz_w = 596;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
