/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) casadi_kf_baseline1_f_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[3] = {0., 1., 0.};
static const casadi_real casadi_c2[3] = {1., 0., 0.};
static const casadi_real casadi_c3[3] = {0., 0., 9.8000000000000007e+00};

/* process:(i0[10],i1[7],i2[7],i3)->(o0[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+3, w1, w2, *w3=w+15, *w4=w+18, *w5=w+21, *w6=w+30, w7, w8, w9, w10, *w11=w+43, *w12=w+46, *w13=w+49, *w14=w+52, *w15=w+61, *w16=w+70, *w17=w+79, w18, w19, *w20=w+88, *w21=w+91, *w22=w+101, *w23=w+111, *w24=w+118, *w25=w+125;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 10, w0);
  /* #1: @1 = 0.166667 */
  w1 = 1.6666666666666666e-01;
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @1 = (@1*@2) */
  w1 *= w2;
  /* #4: @3 = @0[3:6] */
  for (rr=w3, ss=w0+3; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #5: @4 = zeros(3x1) */
  casadi_clear(w4, 3);
  /* #6: @5 = zeros(3x3) */
  casadi_clear(w5, 9);
  /* #7: @6 = zeros(3x3) */
  casadi_clear(w6, 9);
  /* #8: @7 = @0[8] */
  for (rr=(&w7), ss=w0+8; ss!=w0+9; ss+=1) *rr++ = *ss;
  /* #9: @8 = cos(@7) */
  w8 = cos( w7 );
  /* #10: @9 = sin(@7) */
  w9 = sin( w7 );
  /* #11: @9 = (-@9) */
  w9 = (- w9 );
  /* #12: @10 = 0 */
  w10 = 0.;
  /* #13: @11 = horzcat(@8, @9, @10) */
  rr=w11;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  /* #14: @11 = @11' */
  /* #15: @8 = sin(@7) */
  w8 = sin( w7 );
  /* #16: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #17: @9 = 0 */
  w9 = 0.;
  /* #18: @12 = horzcat(@8, @7, @9) */
  rr=w12;
  *rr++ = w8;
  *rr++ = w7;
  *rr++ = w9;
  /* #19: @12 = @12' */
  /* #20: @13 = [[0, 0, 1]] */
  casadi_copy(casadi_c0, 3, w13);
  /* #21: @13 = @13' */
  /* #22: @14 = horzcat(@11, @12, @13) */
  rr=w14;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #23: @15 = @14' */
  for (i=0, rr=w15, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #24: @8 = @0[7] */
  for (rr=(&w8), ss=w0+7; ss!=w0+8; ss+=1) *rr++ = *ss;
  /* #25: @7 = cos(@8) */
  w7 = cos( w8 );
  /* #26: @9 = 0 */
  w9 = 0.;
  /* #27: @10 = sin(@8) */
  w10 = sin( w8 );
  /* #28: @11 = horzcat(@7, @9, @10) */
  rr=w11;
  *rr++ = w7;
  *rr++ = w9;
  *rr++ = w10;
  /* #29: @11 = @11' */
  /* #30: @12 = [[0, 1, 0]] */
  casadi_copy(casadi_c1, 3, w12);
  /* #31: @12 = @12' */
  /* #32: @7 = sin(@8) */
  w7 = sin( w8 );
  /* #33: @7 = (-@7) */
  w7 = (- w7 );
  /* #34: @9 = 0 */
  w9 = 0.;
  /* #35: @8 = cos(@8) */
  w8 = cos( w8 );
  /* #36: @13 = horzcat(@7, @9, @8) */
  rr=w13;
  *rr++ = w7;
  *rr++ = w9;
  *rr++ = w8;
  /* #37: @13 = @13' */
  /* #38: @14 = horzcat(@11, @12, @13) */
  rr=w14;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #39: @16 = @14' */
  for (i=0, rr=w16, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #40: @6 = mac(@15,@16,@6) */
  for (i=0, rr=w6; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #41: @11 = [[1, 0, 0]] */
  casadi_copy(casadi_c2, 3, w11);
  /* #42: @11 = @11' */
  /* #43: @7 = 0 */
  w7 = 0.;
  /* #44: @9 = @0[6] */
  for (rr=(&w9), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #45: @8 = cos(@9) */
  w8 = cos( w9 );
  /* #46: @10 = sin(@9) */
  w10 = sin( w9 );
  /* #47: @10 = (-@10) */
  w10 = (- w10 );
  /* #48: @12 = horzcat(@7, @8, @10) */
  rr=w12;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w10;
  /* #49: @12 = @12' */
  /* #50: @7 = 0 */
  w7 = 0.;
  /* #51: @8 = sin(@9) */
  w8 = sin( w9 );
  /* #52: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #53: @13 = horzcat(@7, @8, @9) */
  rr=w13;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #54: @13 = @13' */
  /* #55: @15 = horzcat(@11, @12, @13) */
  rr=w15;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #56: @16 = @15' */
  for (i=0, rr=w16, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #57: @5 = mac(@6,@16,@5) */
  for (i=0, rr=w5; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w6+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #58: @17 = input[1][0] */
  casadi_copy(arg[1], 7, w17);
  /* #59: @11 = @17[3:6] */
  for (rr=w11, ss=w17+3; ss!=w17+6; ss+=1) *rr++ = *ss;
  /* #60: @4 = mac(@5,@11,@4) */
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w11+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #61: @11 = [0, 0, 9.8] */
  casadi_copy(casadi_c3, 3, w11);
  /* #62: @4 = (@4-@11) */
  for (i=0, rr=w4, cs=w11; i<3; ++i) (*rr++) -= (*cs++);
  /* #63: @11 = zeros(3x1) */
  casadi_clear(w11, 3);
  /* #64: @7 = 1 */
  w7 = 1.;
  /* #65: @8 = @0[7] */
  for (rr=(&w8), ss=w0+7; ss!=w0+8; ss+=1) *rr++ = *ss;
  /* #66: @9 = sin(@8) */
  w9 = sin( w8 );
  /* #67: @10 = @0[6] */
  for (rr=(&w10), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #68: @18 = sin(@10) */
  w18 = sin( w10 );
  /* #69: @9 = (@9*@18) */
  w9 *= w18;
  /* #70: @18 = cos(@8) */
  w18 = cos( w8 );
  /* #71: @9 = (@9/@18) */
  w9 /= w18;
  /* #72: @18 = cos(@10) */
  w18 = cos( w10 );
  /* #73: @19 = sin(@8) */
  w19 = sin( w8 );
  /* #74: @18 = (@18*@19) */
  w18 *= w19;
  /* #75: @19 = cos(@8) */
  w19 = cos( w8 );
  /* #76: @18 = (@18/@19) */
  w18 /= w19;
  /* #77: @12 = horzcat(@7, @9, @18) */
  rr=w12;
  *rr++ = w7;
  *rr++ = w9;
  *rr++ = w18;
  /* #78: @12 = @12' */
  /* #79: @7 = 0 */
  w7 = 0.;
  /* #80: @9 = cos(@10) */
  w9 = cos( w10 );
  /* #81: @18 = sin(@10) */
  w18 = sin( w10 );
  /* #82: @18 = (-@18) */
  w18 = (- w18 );
  /* #83: @13 = horzcat(@7, @9, @18) */
  rr=w13;
  *rr++ = w7;
  *rr++ = w9;
  *rr++ = w18;
  /* #84: @13 = @13' */
  /* #85: @7 = 0 */
  w7 = 0.;
  /* #86: @9 = sin(@10) */
  w9 = sin( w10 );
  /* #87: @18 = cos(@8) */
  w18 = cos( w8 );
  /* #88: @9 = (@9/@18) */
  w9 /= w18;
  /* #89: @10 = cos(@10) */
  w10 = cos( w10 );
  /* #90: @8 = cos(@8) */
  w8 = cos( w8 );
  /* #91: @10 = (@10/@8) */
  w10 /= w8;
  /* #92: @20 = horzcat(@7, @9, @10) */
  rr=w20;
  *rr++ = w7;
  *rr++ = w9;
  *rr++ = w10;
  /* #93: @20 = @20' */
  /* #94: @5 = horzcat(@12, @13, @20) */
  rr=w5;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  /* #95: @6 = @5' */
  for (i=0, rr=w6, cs=w5; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #96: @12 = @17[:3] */
  for (rr=w12, ss=w17+0; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #97: @11 = mac(@6,@12,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w6+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #98: @7 = 1 */
  w7 = 1.;
  /* #99: @21 = vertcat(@3, @4, @11, @7) */
  rr=w21;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  *rr++ = w7;
  /* #100: @22 = (@2*@21) */
  for (i=0, rr=w22, cs=w21; i<10; ++i) (*rr++)  = (w2*(*cs++));
  /* #101: @7 = 2 */
  w7 = 2.;
  /* #102: @22 = (@22/@7) */
  for (i=0, rr=w22; i<10; ++i) (*rr++) /= w7;
  /* #103: @22 = (@0+@22) */
  for (i=0, rr=w22, cr=w0, cs=w22; i<10; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #104: @3 = @22[3:6] */
  for (rr=w3, ss=w22+3; ss!=w22+6; ss+=1) *rr++ = *ss;
  /* #105: @4 = zeros(3x1) */
  casadi_clear(w4, 3);
  /* #106: @6 = zeros(3x3) */
  casadi_clear(w6, 9);
  /* #107: @5 = zeros(3x3) */
  casadi_clear(w5, 9);
  /* #108: @7 = @22[8] */
  for (rr=(&w7), ss=w22+8; ss!=w22+9; ss+=1) *rr++ = *ss;
  /* #109: @9 = cos(@7) */
  w9 = cos( w7 );
  /* #110: @10 = sin(@7) */
  w10 = sin( w7 );
  /* #111: @10 = (-@10) */
  w10 = (- w10 );
  /* #112: @8 = 0 */
  w8 = 0.;
  /* #113: @11 = horzcat(@9, @10, @8) */
  rr=w11;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w8;
  /* #114: @11 = @11' */
  /* #115: @9 = sin(@7) */
  w9 = sin( w7 );
  /* #116: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #117: @10 = 0 */
  w10 = 0.;
  /* #118: @12 = horzcat(@9, @7, @10) */
  rr=w12;
  *rr++ = w9;
  *rr++ = w7;
  *rr++ = w10;
  /* #119: @12 = @12' */
  /* #120: @13 = [[0, 0, 1]] */
  casadi_copy(casadi_c0, 3, w13);
  /* #121: @13 = @13' */
  /* #122: @16 = horzcat(@11, @12, @13) */
  rr=w16;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #123: @15 = @16' */
  for (i=0, rr=w15, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #124: @9 = @22[7] */
  for (rr=(&w9), ss=w22+7; ss!=w22+8; ss+=1) *rr++ = *ss;
  /* #125: @7 = cos(@9) */
  w7 = cos( w9 );
  /* #126: @10 = 0 */
  w10 = 0.;
  /* #127: @8 = sin(@9) */
  w8 = sin( w9 );
  /* #128: @11 = horzcat(@7, @10, @8) */
  rr=w11;
  *rr++ = w7;
  *rr++ = w10;
  *rr++ = w8;
  /* #129: @11 = @11' */
  /* #130: @12 = [[0, 1, 0]] */
  casadi_copy(casadi_c1, 3, w12);
  /* #131: @12 = @12' */
  /* #132: @7 = sin(@9) */
  w7 = sin( w9 );
  /* #133: @7 = (-@7) */
  w7 = (- w7 );
  /* #134: @10 = 0 */
  w10 = 0.;
  /* #135: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #136: @13 = horzcat(@7, @10, @9) */
  rr=w13;
  *rr++ = w7;
  *rr++ = w10;
  *rr++ = w9;
  /* #137: @13 = @13' */
  /* #138: @16 = horzcat(@11, @12, @13) */
  rr=w16;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #139: @14 = @16' */
  for (i=0, rr=w14, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #140: @5 = mac(@15,@14,@5) */
  for (i=0, rr=w5; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w14+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #141: @11 = [[1, 0, 0]] */
  casadi_copy(casadi_c2, 3, w11);
  /* #142: @11 = @11' */
  /* #143: @7 = 0 */
  w7 = 0.;
  /* #144: @10 = @22[6] */
  for (rr=(&w10), ss=w22+6; ss!=w22+7; ss+=1) *rr++ = *ss;
  /* #145: @9 = cos(@10) */
  w9 = cos( w10 );
  /* #146: @8 = sin(@10) */
  w8 = sin( w10 );
  /* #147: @8 = (-@8) */
  w8 = (- w8 );
  /* #148: @12 = horzcat(@7, @9, @8) */
  rr=w12;
  *rr++ = w7;
  *rr++ = w9;
  *rr++ = w8;
  /* #149: @12 = @12' */
  /* #150: @7 = 0 */
  w7 = 0.;
  /* #151: @9 = sin(@10) */
  w9 = sin( w10 );
  /* #152: @10 = cos(@10) */
  w10 = cos( w10 );
  /* #153: @13 = horzcat(@7, @9, @10) */
  rr=w13;
  *rr++ = w7;
  *rr++ = w9;
  *rr++ = w10;
  /* #154: @13 = @13' */
  /* #155: @15 = horzcat(@11, @12, @13) */
  rr=w15;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #156: @14 = @15' */
  for (i=0, rr=w14, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #157: @6 = mac(@5,@14,@6) */
  for (i=0, rr=w6; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w14+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #158: @23 = input[2][0] */
  casadi_copy(arg[2], 7, w23);
  /* #159: @24 = (@17+@23) */
  for (i=0, rr=w24, cr=w17, cs=w23; i<7; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #160: @7 = 2 */
  w7 = 2.;
  /* #161: @24 = (@24/@7) */
  for (i=0, rr=w24; i<7; ++i) (*rr++) /= w7;
  /* #162: @11 = @24[3:6] */
  for (rr=w11, ss=w24+3; ss!=w24+6; ss+=1) *rr++ = *ss;
  /* #163: @4 = mac(@6,@11,@4) */
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w6+j, tt=w11+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #164: @11 = [0, 0, 9.8] */
  casadi_copy(casadi_c3, 3, w11);
  /* #165: @4 = (@4-@11) */
  for (i=0, rr=w4, cs=w11; i<3; ++i) (*rr++) -= (*cs++);
  /* #166: @11 = zeros(3x1) */
  casadi_clear(w11, 3);
  /* #167: @7 = 1 */
  w7 = 1.;
  /* #168: @9 = @22[7] */
  for (rr=(&w9), ss=w22+7; ss!=w22+8; ss+=1) *rr++ = *ss;
  /* #169: @10 = sin(@9) */
  w10 = sin( w9 );
  /* #170: @8 = @22[6] */
  for (rr=(&w8), ss=w22+6; ss!=w22+7; ss+=1) *rr++ = *ss;
  /* #171: @18 = sin(@8) */
  w18 = sin( w8 );
  /* #172: @10 = (@10*@18) */
  w10 *= w18;
  /* #173: @18 = cos(@9) */
  w18 = cos( w9 );
  /* #174: @10 = (@10/@18) */
  w10 /= w18;
  /* #175: @18 = cos(@8) */
  w18 = cos( w8 );
  /* #176: @19 = sin(@9) */
  w19 = sin( w9 );
  /* #177: @18 = (@18*@19) */
  w18 *= w19;
  /* #178: @19 = cos(@9) */
  w19 = cos( w9 );
  /* #179: @18 = (@18/@19) */
  w18 /= w19;
  /* #180: @12 = horzcat(@7, @10, @18) */
  rr=w12;
  *rr++ = w7;
  *rr++ = w10;
  *rr++ = w18;
  /* #181: @12 = @12' */
  /* #182: @7 = 0 */
  w7 = 0.;
  /* #183: @10 = cos(@8) */
  w10 = cos( w8 );
  /* #184: @18 = sin(@8) */
  w18 = sin( w8 );
  /* #185: @18 = (-@18) */
  w18 = (- w18 );
  /* #186: @13 = horzcat(@7, @10, @18) */
  rr=w13;
  *rr++ = w7;
  *rr++ = w10;
  *rr++ = w18;
  /* #187: @13 = @13' */
  /* #188: @7 = 0 */
  w7 = 0.;
  /* #189: @10 = sin(@8) */
  w10 = sin( w8 );
  /* #190: @18 = cos(@9) */
  w18 = cos( w9 );
  /* #191: @10 = (@10/@18) */
  w10 /= w18;
  /* #192: @8 = cos(@8) */
  w8 = cos( w8 );
  /* #193: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #194: @8 = (@8/@9) */
  w8 /= w9;
  /* #195: @20 = horzcat(@7, @10, @8) */
  rr=w20;
  *rr++ = w7;
  *rr++ = w10;
  *rr++ = w8;
  /* #196: @20 = @20' */
  /* #197: @6 = horzcat(@12, @13, @20) */
  rr=w6;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  /* #198: @5 = @6' */
  for (i=0, rr=w5, cs=w6; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #199: @12 = @24[:3] */
  for (rr=w12, ss=w24+0; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #200: @11 = mac(@5,@12,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #201: @7 = 1 */
  w7 = 1.;
  /* #202: @22 = vertcat(@3, @4, @11, @7) */
  rr=w22;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  *rr++ = w7;
  /* #203: @25 = (2.*@22) */
  for (i=0, rr=w25, cs=w22; i<10; ++i) *rr++ = (2.* *cs++ );
  /* #204: @21 = (@21+@25) */
  for (i=0, rr=w21, cs=w25; i<10; ++i) (*rr++) += (*cs++);
  /* #205: @22 = (@2*@22) */
  for (i=0, rr=w22, cs=w22; i<10; ++i) (*rr++)  = (w2*(*cs++));
  /* #206: @7 = 2 */
  w7 = 2.;
  /* #207: @22 = (@22/@7) */
  for (i=0, rr=w22; i<10; ++i) (*rr++) /= w7;
  /* #208: @22 = (@0+@22) */
  for (i=0, rr=w22, cr=w0, cs=w22; i<10; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #209: @3 = @22[3:6] */
  for (rr=w3, ss=w22+3; ss!=w22+6; ss+=1) *rr++ = *ss;
  /* #210: @4 = zeros(3x1) */
  casadi_clear(w4, 3);
  /* #211: @5 = zeros(3x3) */
  casadi_clear(w5, 9);
  /* #212: @6 = zeros(3x3) */
  casadi_clear(w6, 9);
  /* #213: @7 = @22[8] */
  for (rr=(&w7), ss=w22+8; ss!=w22+9; ss+=1) *rr++ = *ss;
  /* #214: @10 = cos(@7) */
  w10 = cos( w7 );
  /* #215: @8 = sin(@7) */
  w8 = sin( w7 );
  /* #216: @8 = (-@8) */
  w8 = (- w8 );
  /* #217: @9 = 0 */
  w9 = 0.;
  /* #218: @11 = horzcat(@10, @8, @9) */
  rr=w11;
  *rr++ = w10;
  *rr++ = w8;
  *rr++ = w9;
  /* #219: @11 = @11' */
  /* #220: @10 = sin(@7) */
  w10 = sin( w7 );
  /* #221: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #222: @8 = 0 */
  w8 = 0.;
  /* #223: @12 = horzcat(@10, @7, @8) */
  rr=w12;
  *rr++ = w10;
  *rr++ = w7;
  *rr++ = w8;
  /* #224: @12 = @12' */
  /* #225: @13 = [[0, 0, 1]] */
  casadi_copy(casadi_c0, 3, w13);
  /* #226: @13 = @13' */
  /* #227: @14 = horzcat(@11, @12, @13) */
  rr=w14;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #228: @15 = @14' */
  for (i=0, rr=w15, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #229: @10 = @22[7] */
  for (rr=(&w10), ss=w22+7; ss!=w22+8; ss+=1) *rr++ = *ss;
  /* #230: @7 = cos(@10) */
  w7 = cos( w10 );
  /* #231: @8 = 0 */
  w8 = 0.;
  /* #232: @9 = sin(@10) */
  w9 = sin( w10 );
  /* #233: @11 = horzcat(@7, @8, @9) */
  rr=w11;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #234: @11 = @11' */
  /* #235: @12 = [[0, 1, 0]] */
  casadi_copy(casadi_c1, 3, w12);
  /* #236: @12 = @12' */
  /* #237: @7 = sin(@10) */
  w7 = sin( w10 );
  /* #238: @7 = (-@7) */
  w7 = (- w7 );
  /* #239: @8 = 0 */
  w8 = 0.;
  /* #240: @10 = cos(@10) */
  w10 = cos( w10 );
  /* #241: @13 = horzcat(@7, @8, @10) */
  rr=w13;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w10;
  /* #242: @13 = @13' */
  /* #243: @14 = horzcat(@11, @12, @13) */
  rr=w14;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #244: @16 = @14' */
  for (i=0, rr=w16, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #245: @6 = mac(@15,@16,@6) */
  for (i=0, rr=w6; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #246: @11 = [[1, 0, 0]] */
  casadi_copy(casadi_c2, 3, w11);
  /* #247: @11 = @11' */
  /* #248: @7 = 0 */
  w7 = 0.;
  /* #249: @8 = @22[6] */
  for (rr=(&w8), ss=w22+6; ss!=w22+7; ss+=1) *rr++ = *ss;
  /* #250: @10 = cos(@8) */
  w10 = cos( w8 );
  /* #251: @9 = sin(@8) */
  w9 = sin( w8 );
  /* #252: @9 = (-@9) */
  w9 = (- w9 );
  /* #253: @12 = horzcat(@7, @10, @9) */
  rr=w12;
  *rr++ = w7;
  *rr++ = w10;
  *rr++ = w9;
  /* #254: @12 = @12' */
  /* #255: @7 = 0 */
  w7 = 0.;
  /* #256: @10 = sin(@8) */
  w10 = sin( w8 );
  /* #257: @8 = cos(@8) */
  w8 = cos( w8 );
  /* #258: @13 = horzcat(@7, @10, @8) */
  rr=w13;
  *rr++ = w7;
  *rr++ = w10;
  *rr++ = w8;
  /* #259: @13 = @13' */
  /* #260: @15 = horzcat(@11, @12, @13) */
  rr=w15;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #261: @16 = @15' */
  for (i=0, rr=w16, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #262: @5 = mac(@6,@16,@5) */
  for (i=0, rr=w5; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w6+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #263: @17 = (@17+@23) */
  for (i=0, rr=w17, cs=w23; i<7; ++i) (*rr++) += (*cs++);
  /* #264: @7 = 2 */
  w7 = 2.;
  /* #265: @17 = (@17/@7) */
  for (i=0, rr=w17; i<7; ++i) (*rr++) /= w7;
  /* #266: @11 = @17[3:6] */
  for (rr=w11, ss=w17+3; ss!=w17+6; ss+=1) *rr++ = *ss;
  /* #267: @4 = mac(@5,@11,@4) */
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w11+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #268: @11 = [0, 0, 9.8] */
  casadi_copy(casadi_c3, 3, w11);
  /* #269: @4 = (@4-@11) */
  for (i=0, rr=w4, cs=w11; i<3; ++i) (*rr++) -= (*cs++);
  /* #270: @11 = zeros(3x1) */
  casadi_clear(w11, 3);
  /* #271: @7 = 1 */
  w7 = 1.;
  /* #272: @10 = @22[7] */
  for (rr=(&w10), ss=w22+7; ss!=w22+8; ss+=1) *rr++ = *ss;
  /* #273: @8 = sin(@10) */
  w8 = sin( w10 );
  /* #274: @9 = @22[6] */
  for (rr=(&w9), ss=w22+6; ss!=w22+7; ss+=1) *rr++ = *ss;
  /* #275: @18 = sin(@9) */
  w18 = sin( w9 );
  /* #276: @8 = (@8*@18) */
  w8 *= w18;
  /* #277: @18 = cos(@10) */
  w18 = cos( w10 );
  /* #278: @8 = (@8/@18) */
  w8 /= w18;
  /* #279: @18 = cos(@9) */
  w18 = cos( w9 );
  /* #280: @19 = sin(@10) */
  w19 = sin( w10 );
  /* #281: @18 = (@18*@19) */
  w18 *= w19;
  /* #282: @19 = cos(@10) */
  w19 = cos( w10 );
  /* #283: @18 = (@18/@19) */
  w18 /= w19;
  /* #284: @12 = horzcat(@7, @8, @18) */
  rr=w12;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w18;
  /* #285: @12 = @12' */
  /* #286: @7 = 0 */
  w7 = 0.;
  /* #287: @8 = cos(@9) */
  w8 = cos( w9 );
  /* #288: @18 = sin(@9) */
  w18 = sin( w9 );
  /* #289: @18 = (-@18) */
  w18 = (- w18 );
  /* #290: @13 = horzcat(@7, @8, @18) */
  rr=w13;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w18;
  /* #291: @13 = @13' */
  /* #292: @7 = 0 */
  w7 = 0.;
  /* #293: @8 = sin(@9) */
  w8 = sin( w9 );
  /* #294: @18 = cos(@10) */
  w18 = cos( w10 );
  /* #295: @8 = (@8/@18) */
  w8 /= w18;
  /* #296: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #297: @10 = cos(@10) */
  w10 = cos( w10 );
  /* #298: @9 = (@9/@10) */
  w9 /= w10;
  /* #299: @20 = horzcat(@7, @8, @9) */
  rr=w20;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #300: @20 = @20' */
  /* #301: @5 = horzcat(@12, @13, @20) */
  rr=w5;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  /* #302: @6 = @5' */
  for (i=0, rr=w6, cs=w5; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #303: @12 = @17[:3] */
  for (rr=w12, ss=w17+0; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #304: @11 = mac(@6,@12,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w6+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #305: @7 = 1 */
  w7 = 1.;
  /* #306: @22 = vertcat(@3, @4, @11, @7) */
  rr=w22;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  *rr++ = w7;
  /* #307: @25 = (2.*@22) */
  for (i=0, rr=w25, cs=w22; i<10; ++i) *rr++ = (2.* *cs++ );
  /* #308: @21 = (@21+@25) */
  for (i=0, rr=w21, cs=w25; i<10; ++i) (*rr++) += (*cs++);
  /* #309: @22 = (@2*@22) */
  for (i=0, rr=w22, cs=w22; i<10; ++i) (*rr++)  = (w2*(*cs++));
  /* #310: @22 = (@0+@22) */
  for (i=0, rr=w22, cr=w0, cs=w22; i<10; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #311: @3 = @22[3:6] */
  for (rr=w3, ss=w22+3; ss!=w22+6; ss+=1) *rr++ = *ss;
  /* #312: @4 = zeros(3x1) */
  casadi_clear(w4, 3);
  /* #313: @6 = zeros(3x3) */
  casadi_clear(w6, 9);
  /* #314: @5 = zeros(3x3) */
  casadi_clear(w5, 9);
  /* #315: @2 = @22[8] */
  for (rr=(&w2), ss=w22+8; ss!=w22+9; ss+=1) *rr++ = *ss;
  /* #316: @7 = cos(@2) */
  w7 = cos( w2 );
  /* #317: @8 = sin(@2) */
  w8 = sin( w2 );
  /* #318: @8 = (-@8) */
  w8 = (- w8 );
  /* #319: @9 = 0 */
  w9 = 0.;
  /* #320: @11 = horzcat(@7, @8, @9) */
  rr=w11;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #321: @11 = @11' */
  /* #322: @7 = sin(@2) */
  w7 = sin( w2 );
  /* #323: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #324: @8 = 0 */
  w8 = 0.;
  /* #325: @12 = horzcat(@7, @2, @8) */
  rr=w12;
  *rr++ = w7;
  *rr++ = w2;
  *rr++ = w8;
  /* #326: @12 = @12' */
  /* #327: @13 = [[0, 0, 1]] */
  casadi_copy(casadi_c0, 3, w13);
  /* #328: @13 = @13' */
  /* #329: @16 = horzcat(@11, @12, @13) */
  rr=w16;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #330: @15 = @16' */
  for (i=0, rr=w15, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #331: @7 = @22[7] */
  for (rr=(&w7), ss=w22+7; ss!=w22+8; ss+=1) *rr++ = *ss;
  /* #332: @2 = cos(@7) */
  w2 = cos( w7 );
  /* #333: @8 = 0 */
  w8 = 0.;
  /* #334: @9 = sin(@7) */
  w9 = sin( w7 );
  /* #335: @11 = horzcat(@2, @8, @9) */
  rr=w11;
  *rr++ = w2;
  *rr++ = w8;
  *rr++ = w9;
  /* #336: @11 = @11' */
  /* #337: @12 = [[0, 1, 0]] */
  casadi_copy(casadi_c1, 3, w12);
  /* #338: @12 = @12' */
  /* #339: @2 = sin(@7) */
  w2 = sin( w7 );
  /* #340: @2 = (-@2) */
  w2 = (- w2 );
  /* #341: @8 = 0 */
  w8 = 0.;
  /* #342: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #343: @13 = horzcat(@2, @8, @7) */
  rr=w13;
  *rr++ = w2;
  *rr++ = w8;
  *rr++ = w7;
  /* #344: @13 = @13' */
  /* #345: @16 = horzcat(@11, @12, @13) */
  rr=w16;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #346: @14 = @16' */
  for (i=0, rr=w14, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #347: @5 = mac(@15,@14,@5) */
  for (i=0, rr=w5; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w14+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #348: @11 = [[1, 0, 0]] */
  casadi_copy(casadi_c2, 3, w11);
  /* #349: @11 = @11' */
  /* #350: @2 = 0 */
  w2 = 0.;
  /* #351: @8 = @22[6] */
  for (rr=(&w8), ss=w22+6; ss!=w22+7; ss+=1) *rr++ = *ss;
  /* #352: @7 = cos(@8) */
  w7 = cos( w8 );
  /* #353: @9 = sin(@8) */
  w9 = sin( w8 );
  /* #354: @9 = (-@9) */
  w9 = (- w9 );
  /* #355: @12 = horzcat(@2, @7, @9) */
  rr=w12;
  *rr++ = w2;
  *rr++ = w7;
  *rr++ = w9;
  /* #356: @12 = @12' */
  /* #357: @2 = 0 */
  w2 = 0.;
  /* #358: @7 = sin(@8) */
  w7 = sin( w8 );
  /* #359: @8 = cos(@8) */
  w8 = cos( w8 );
  /* #360: @13 = horzcat(@2, @7, @8) */
  rr=w13;
  *rr++ = w2;
  *rr++ = w7;
  *rr++ = w8;
  /* #361: @13 = @13' */
  /* #362: @15 = horzcat(@11, @12, @13) */
  rr=w15;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #363: @14 = @15' */
  for (i=0, rr=w14, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #364: @6 = mac(@5,@14,@6) */
  for (i=0, rr=w6; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w14+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #365: @11 = @23[3:6] */
  for (rr=w11, ss=w23+3; ss!=w23+6; ss+=1) *rr++ = *ss;
  /* #366: @4 = mac(@6,@11,@4) */
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w6+j, tt=w11+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #367: @11 = [0, 0, 9.8] */
  casadi_copy(casadi_c3, 3, w11);
  /* #368: @4 = (@4-@11) */
  for (i=0, rr=w4, cs=w11; i<3; ++i) (*rr++) -= (*cs++);
  /* #369: @11 = zeros(3x1) */
  casadi_clear(w11, 3);
  /* #370: @2 = 1 */
  w2 = 1.;
  /* #371: @7 = @22[7] */
  for (rr=(&w7), ss=w22+7; ss!=w22+8; ss+=1) *rr++ = *ss;
  /* #372: @8 = sin(@7) */
  w8 = sin( w7 );
  /* #373: @9 = @22[6] */
  for (rr=(&w9), ss=w22+6; ss!=w22+7; ss+=1) *rr++ = *ss;
  /* #374: @10 = sin(@9) */
  w10 = sin( w9 );
  /* #375: @8 = (@8*@10) */
  w8 *= w10;
  /* #376: @10 = cos(@7) */
  w10 = cos( w7 );
  /* #377: @8 = (@8/@10) */
  w8 /= w10;
  /* #378: @10 = cos(@9) */
  w10 = cos( w9 );
  /* #379: @18 = sin(@7) */
  w18 = sin( w7 );
  /* #380: @10 = (@10*@18) */
  w10 *= w18;
  /* #381: @18 = cos(@7) */
  w18 = cos( w7 );
  /* #382: @10 = (@10/@18) */
  w10 /= w18;
  /* #383: @12 = horzcat(@2, @8, @10) */
  rr=w12;
  *rr++ = w2;
  *rr++ = w8;
  *rr++ = w10;
  /* #384: @12 = @12' */
  /* #385: @2 = 0 */
  w2 = 0.;
  /* #386: @8 = cos(@9) */
  w8 = cos( w9 );
  /* #387: @10 = sin(@9) */
  w10 = sin( w9 );
  /* #388: @10 = (-@10) */
  w10 = (- w10 );
  /* #389: @13 = horzcat(@2, @8, @10) */
  rr=w13;
  *rr++ = w2;
  *rr++ = w8;
  *rr++ = w10;
  /* #390: @13 = @13' */
  /* #391: @2 = 0 */
  w2 = 0.;
  /* #392: @8 = sin(@9) */
  w8 = sin( w9 );
  /* #393: @10 = cos(@7) */
  w10 = cos( w7 );
  /* #394: @8 = (@8/@10) */
  w8 /= w10;
  /* #395: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #396: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #397: @9 = (@9/@7) */
  w9 /= w7;
  /* #398: @20 = horzcat(@2, @8, @9) */
  rr=w20;
  *rr++ = w2;
  *rr++ = w8;
  *rr++ = w9;
  /* #399: @20 = @20' */
  /* #400: @6 = horzcat(@12, @13, @20) */
  rr=w6;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  /* #401: @5 = @6' */
  for (i=0, rr=w5, cs=w6; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #402: @12 = @23[:3] */
  for (rr=w12, ss=w23+0; ss!=w23+3; ss+=1) *rr++ = *ss;
  /* #403: @11 = mac(@5,@12,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #404: @2 = 1 */
  w2 = 1.;
  /* #405: @22 = vertcat(@3, @4, @11, @2) */
  rr=w22;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  *rr++ = w2;
  /* #406: @21 = (@21+@22) */
  for (i=0, rr=w21, cs=w22; i<10; ++i) (*rr++) += (*cs++);
  /* #407: @21 = (@1*@21) */
  for (i=0, rr=w21, cs=w21; i<10; ++i) (*rr++)  = (w1*(*cs++));
  /* #408: @0 = (@0+@21) */
  for (i=0, rr=w0, cs=w21; i<10; ++i) (*rr++) += (*cs++);
  /* #409: output[0][0] = @0 */
  casadi_copy(w0, 10, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int process(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int process_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int process_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void process_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int process_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void process_release(int mem) {
}

CASADI_SYMBOL_EXPORT void process_incref(void) {
}

CASADI_SYMBOL_EXPORT void process_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int process_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int process_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real process_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* process_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* process_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* process_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* process_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int process_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 135;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
